CopilotKit/CopilotKit

CopilotKit/packages/backend/package.json
CopilotKit/packages/backend/tsup.config.ts
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-core/tsup.config.ts
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-textarea/src/components/hovering-toolbar/text-insertion-prompt-box/hovering-insertion-prompt-box-core.tsx
CopilotKit/packages/react-textarea/tsup.config.ts
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/react-ui/tsup.config.ts
CopilotKit/packages/shared/package.json
CopilotKit/packages/shared/tsup.config.ts

The `dev` script was using the same `tssup.config.ts` script as `build`.
Whenever you'd make a change to any dependency, `clean: true` causes the removal of the entire `dist` folder. This results in a few miliseconds where the dependency cannot be found, enough to cause an error.
Removing `clean: true` from `tsup.config.ts` and specifying it as a `--clean` flag specifically for `build`.

fix: hot reload when dependencies change in dev

---

CopilotKit/packages/backend/package.json
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/shared/package.json

Still not entirely sure why this only happens with `<CopilotTextarea>`, but seems that removing the tsup `--treeshake` flag solves the issue. There are still type issues that show up in the IDE, will tackle in a separate PR.

fix: import issues related to treeshaking

---

CopilotKit/packages/backend/src/lib/openai-adapter.ts

Fixes #193 
The problem was that the default for the `openai` instance var gets instantiated before the constructor is run, thus resulting in an error when the env variable is missing.

Fix: OpenAI gets instantiated before running constructor

---

CopilotKit/examples/next-openai/src/app/helloworld/page.tsx
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/context/index.ts
CopilotKit/packages/react-core/src/index.tsx
CopilotKit/packages/react-core/src/lib/copilot-task.ts
CopilotKit/packages/react-core/src/lib/index.ts

This adds `CopilotTask`, a class for running custom tasks (function calling) without chat.
`instructions` tells the GPT what to do.
There is an optional `data` parameter to provide context.
In addition, it can take the current state and functions from an optional `context` object (using data and functions previously defined via `useMakeCopilotReadable` and `useMakeCopilotActionable`.
It can also take an array of `functions` (type: `AnnotatedFunction`) to make an independent, standalone task.
Example:
```ts
const context = useCopilotContext();
const randomSlideTask = new CopilotTask({
instructions: "Make a random slide",
});
await randomSlideTask.run(context);
```

Add CopilotTask class

---

CopilotKit/packages/react-textarea/src/lib/debouncer.ts

Resolved a type mismatch issue in `debouncer.ts` by changing the `timeoutId` type from `number` to `NodeJS.Timeout`, aligning with the correct return type of `setTimeout` in NodeJS environments.
This was causing a build error

fix(react-textarea): Correct `timeoutId` type in Debouncer

---

CopilotKit/examples/next-openai/src/app/api/copilotkit/gpt-newspaper/route.ts
CopilotKit/examples/next-openai/src/app/presentation-agent/page.tsx
CopilotKit/examples/next-openai/src/app/presentation-agent/styles.css

A demo with the agent behind GPT Newspaper researching for a presentation.
Utilizes Tavily and LangGraph in the backend.
To run this example:
- clone https://github.com/mme/gpt-newspaper
- follow the instructions in NOTES.md
- go to http://localhost:3000/presentation-agent and ask copilot to research something

add gpt newspaper backed demo

---

CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/base-copilot-textarea.tsx
CopilotKit/packages/react-textarea/src/components/hovering-toolbar/hovering-toolbar-components.tsx
CopilotKit/packages/react-textarea/src/components/hovering-toolbar/hovering-toolbar.tsx
CopilotKit/packages/react-textarea/src/components/hovering-toolbar/text-insertion-prompt-box/hovering-insertion-prompt-box-core.tsx

Clear CopilotTextarea on blur.

clear CopilotTextarea on blur

---

CopilotKit/packages/react-ui/src/css/messages.css

Preserve the whitespace in chat user inputs. Fix #294

Preserve whitespace in user input

---

CopilotKit/examples/next-openai/src/app/presentation/components/main/Presentation.tsx
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/hooks/use-chat.ts

Hi @arnoldmukisa @alsong,
We recently moved `messages` to the global context, just in a slightly different way :) This PR merges the existing approach with your PR.
Also nice idea loading/restoring the message history from local storage! Since our users might have different strategies on storing the message history, I cannot enable this for all users. However, since we now gained the capability to access the messages array from the context object, it is now very simple to just load the messages in application code.
```ts
// Load messages from local storage
const { messages, setMessages } = useCopilotContext();
// save to local storage when messages change
useEffect(() => {
if (messages.length !== 0) {
localStorage.setItem("copilotkit-messages", JSON.stringify(messages));
}
}, …
```

Merge changes and ideas from Arnold and Alsong

---

CopilotKit/.changeset/config.json

Update the changeset config to "fixed" or "locked" versioning. This causes all of our packages to have the same version from the next release onwards.

Switch to fixed versioning

---

CopilotKit/examples/next-openai/src/app/textarea/page.tsx
CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-insertion-function.tsx

This PR fixes a bug where the API key was not sent when editing a textarea via the overlay

Send API key when editing text

---

CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/base-copilot-textarea.tsx
CopilotKit/packages/react-textarea/src/hooks/base-copilot-textarea-implementation/use-autosuggestions.ts
CopilotKit/packages/react-textarea/src/types/base/base-autosuggestions-config.tsx

Fixes https://github.com/CopilotKit/CopilotKit/issues/383
This PR sets the foundation to enable "accept suggestion on tap".
The idea here is simply: Allow "accept suggestion" on tap on mobile (`touchstart` event) using the same mechanism that's used to accept suggestions using the tab key.
However, this does not provide a full solution just yet, because setting the added `shouldAcceptAutosuggestionOnTouch` to just "true" means all suggestions will be approved on tap.
One good UX solution to this would be to figure out where the tap has happened, and approve the suggestion if the user tapped at specific locations (to be determined by the developer implementing this and their team).
I already have a solution for this, but I would need to pass several properties when calling …

feat(config): enable accepting suggestion on mobile on tap

---

CopilotKit/packages/runtime-client-gql/codegen.ts
CopilotKit/packages/runtime-client-gql/package.json
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
CopilotKit/packages/runtime-client-gql/src/graphql/definitions/mutations.ts
CopilotKit/packages/runtime/package.json
CopilotKit/pnpm-lock.yaml
CopilotKit/turbo.json

This PR makes it effortless to develop locally with `turbo run dev`.
* Automatically generates the GraphQL schema after each build, using the [tsup onSuccess callback](https://tsup.egoist.dev/#onsuccess)
* Automatically runs `graphql-codegen:watch` whenever running `dev` for the `runtime-client-gql` package, which watches for changes and regenrates the client

feat(devex): automatically watch and generate gql schema and client

---

CopilotKit/examples/next-openai/src/app/api/copilotkit/route.ts
CopilotKit/examples/next-openai/src/app/presentation/page.tsx
CopilotKit/packages/runtime/package.json
CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
CopilotKit/packages/runtime/src/lib/integrations/nextjs/app-router.ts
CopilotKit/packages/runtime/src/lib/integrations/nextjs/pages-router.ts
CopilotKit/packages/runtime/src/lib/integrations/node-http/index.ts
CopilotKit/packages/runtime/src/lib/integrations/shared.ts
CopilotKit/packages/runtime/src/lib/logger.ts
CopilotKit/pnpm-lock.yaml

* Uses [pino](https://www.npmjs.com/package/pino) with [pino-pretty](https://github.com/pinojs/pino-pretty)
* Supports 4 log level: `error`, `warn`, `info`, `debug` (default is `error`)
* Ability to set log level in two ways:
* `LOG_LEVEL` environment variable, this always takes priority
* Manually when creating the Copilot Runtime endpoint via the `logLevel` optional parameter
* We also use the same logger on Yoga GraphQL for consistency. So if a user has set the log level to `debug`, they will also get Yoga GraphQL debug logs, etcetera.
* Added a bunch of `debug` logs in various places (instantiation, resolver).
Sample logs from a request:

feat(runtime): logging

---

CopilotKit/packages/runtime/src/lib/integrations/shared.ts

A missing type parameter was leading to a type error (because the type defaults to an empty array)

Fix missing any type parameter

---

CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/runtime-client-gql/package.json
CopilotKit/packages/shared/package.json
CopilotKit/turbo.json

Adds two convenient commands to the monorepo:
```
turbo run link:global
turbo run unlink:global
```
To easily use `pnpm link --global` and `pnpm unlink --global` without having to `cd` into each individual package.

feat(repo): global link and unlink turbo commands

---

CopilotKit/packages/react-ui/src/components/chat/Chat.tsx

This is based on the issue raised here - #499 
Currently, `onSubmitMessage` is being awaited, then the user message is appended/visible.
I changed this behavior so that the user message is already visible before calling `onSubmitMessage`.
**Changes made -**
1. The message object is created immediately at the beginning of the function.
2. The appendMessage(message) call is moved before the onSubmitMessage call. This ensures that the user's message is visible in the chat interface before any additional processing occurs.

fix: append user message before calling onSubmitMessage

---

CopilotKit/packages/react-textarea/src/components/copilot-textarea/copilot-textarea.tsx
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/Popup.tsx
CopilotKit/packages/react-ui/src/components/chat/Sidebar.tsx
docs/next.config.mjs
docs/pages/reference/components/CopilotChat.mdx
docs/pages/reference/components/CopilotPopup.mdx
docs/pages/reference/components/CopilotSidebar.mdx
docs/pages/reference/components/CopilotTextarea.mdx

- Add "Look & Feel" sections to each reference Component
- Add link to GitHub type definition for `Textarea.autosuggestionsConfig`. Nesting of properties is currently not supported in our docs generator which makes it hard to manually maintain these. Will need to tackle later.

fix(docs): update docs

---

CopilotKit/packages/react-ui/package.json
CopilotKit/pnpm-lock.yaml

We've received reports of failed installations of CopilotKit, which is likely caused by a broken release of `headlessui/react@v2.1.2`. 
This PR temporarily pins the package to `v2.1.1`.
More information:
https://github.com/tailwindlabs/headlessui/issues/3430

fix(react-ui): pin headless-ui to v2.1.1

---

docs/pages/concepts/self-hosting.mdx

Update grammar and spelling
Service Adapters are responsible for executing the request with the LLM and standardizing the request/response format in a way that the Copilot Runtime can understand.

chore(docs): Fix grammar and spelling in the "Self Hosting" section

---

CopilotKit/examples/next-openai/CHANGELOG.md
CopilotKit/examples/next-openai/package.json
CopilotKit/examples/next-pages-router/CHANGELOG.md
CopilotKit/examples/next-pages-router/package.json
CopilotKit/examples/node-express/CHANGELOG.md
CopilotKit/examples/node-express/package.json
CopilotKit/examples/node-http/CHANGELOG.md
CopilotKit/examples/node-http/package.json
CopilotKit/packages/react-core/CHANGELOG.md
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-textarea/CHANGELOG.md
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-ui/CHANGELOG.md
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/runtime-client-gql/CHANGELOG.md
CopilotKit/packages/runtime-client-gql/package.json
CopilotKit/packages/runtime/CHANGELOG.md
CopilotKit/packages/runtime/package.json
CopilotKit/packages/shared/CHANGELOG.md
CopilotKit/packages/shared/package.json
CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
CopilotKit/utilities/eslint-config-custom/package.json
CopilotKit/utilities/tailwind-config/CHANGELOG.md
CopilotKit/utilities/tailwind-config/package.json
CopilotKit/utilities/tsconfig/CHANGELOG.md
CopilotKit/utilities/tsconfig/package.json

- inject minified css in bundle
- removes the need to import `styles.css` manually
- empty `styles.css` included in the build for backwards compatibility
- uses tsup's `injectStyles` with `postcss` to bundle and minify the CSS, then inject it as a style tag
- currently uses my fork of `tsup` where I added support for async function in `injectStyles` (must-have for postcss), a PR from my fork to the main library will follow shortly
- remove material-ui, and use `react-icons` for icons (same icons as before)
- remove unused `IncludedFilesPreview` component
- updated docs
- Updated dependencies
- @copilotkit/runtime@1.2.1
- @copilotkit/shared@1.2.1

Release v1.2.1

---

README.md

Fixed the existing documentation contribution link to the new one. 
Reference: https://docs.copilotkit.ai/contributing/docs-contributions#how-to-contribute

fix: update docs contribution link

---

docs/components/react/coagents/coagents-features.tsx
docs/content/docs/coagents/index.mdx

Fixes: #713 
The cards which weren't visible in dark mode are visible now.
**In Light Mode** -
**In Dark Mode** -
**In Light Mode** -
**In Dark Mode** -
Feel free to ask for more changes if required

Fix: Cards not visible in Dark Mode #713

---

docs/content/docs/(root)/guides/generative-ui.mdx
docs/content/docs/reference/hooks/useCopilotAction.mdx

This PR fixes 2 issues with the docs:
- Adding an explanation on the new `followUp` property available for generative UI action
- Aligning the `renderAndWait` method arguments with the actual signature expected

fix(docs): docs misalignment fixes

---

CopilotKit/packages/react-ui/src/components/dev-console/console.tsx

A fix to the debug button overlapping the CopilotKit logo in chat, or otherwise floating in unexpected locations in the page

fix(debug): fix floating debug button overlapping CopilotKit logo

---

examples/coagents-ai-researcher/agent/ai_researcher/demo.py
examples/coagents-qa-native/agent/my_agent/demo.py
examples/coagents-qa-text/agent/my_agent/demo.py
examples/coagents-qa/agent/my_agent/demo.py
examples/coagents-research-canvas/agent/research_canvas/demo.py
examples/coagents-shared-state/agent/my_agent/demo.py
examples/coagents-starter/agent/my_agent/demo.py
examples/coagents-wait-user-input/agent/my_agent/demo.py

For our example apps, the FastAPI host was previously set to `127.0.0.1` which does not allow connection from `localhost`. By setting the host to `0.0.0.0`, we allow connection from anywhere.

fix(examples): coagents host set to 0.0.0.0

---

CopilotKit/examples/next-openai/CHANGELOG.md
CopilotKit/examples/next-openai/package.json
CopilotKit/examples/next-pages-router/CHANGELOG.md
CopilotKit/examples/next-pages-router/package.json
CopilotKit/examples/node-express/CHANGELOG.md
CopilotKit/examples/node-express/package.json
CopilotKit/examples/node-http/CHANGELOG.md
CopilotKit/examples/node-http/package.json
CopilotKit/packages/react-core/CHANGELOG.md
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-textarea/CHANGELOG.md
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-ui/CHANGELOG.md
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/runtime-client-gql/CHANGELOG.md
CopilotKit/packages/runtime-client-gql/package.json
CopilotKit/packages/runtime/CHANGELOG.md
CopilotKit/packages/runtime/package.json
CopilotKit/packages/shared/CHANGELOG.md
CopilotKit/packages/shared/package.json
CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
CopilotKit/utilities/eslint-config-custom/package.json
CopilotKit/utilities/tailwind-config/CHANGELOG.md
CopilotKit/utilities/tailwind-config/package.json
CopilotKit/utilities/tsconfig/CHANGELOG.md
CopilotKit/utilities/tsconfig/package.json

1. Removes the usage of the `crypto` Node pacakge, instaed uses `uuid`. This ensures that non-Next.js React apps can use CopilotKit.
2. Fixes Nest.js runtime docs

Release v1.3.6

---

CopilotKit/packages/react-core/src/components/copilot-provider/copilot-messages.tsx
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/context/copilot-messages-context.tsx
CopilotKit/packages/react-core/src/context/index.ts
CopilotKit/packages/react-core/src/hooks/use-coagent.ts
CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
CopilotKit/packages/react-core/src/utils/extract.ts
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/Suggestion.tsx
CopilotKit/packages/react-ui/src/components/dev-console/console.tsx
CopilotKit/packages/react-ui/src/components/dev-console/utils.ts
CopilotKit/packages/react-ui/src/hooks/use-push-to-talk.tsx
CopilotKit/scripts/release/prerelease.sh

This PR moves "messages" from the main context to a new cozy home. This is because the frequent update of the messages causes an update to the whole tree of main context.
With such split in place, the update of messages now will not rerender all tree. This is especially important because of how update of messages work: Messages will be updated when the chat streams, therefore, a re-render for almost every token

fix(context): split context to avoid excessive re-renders

---

community/content/README.md

This PR fixes a broken link in the Resources section of the documentation. Previously, clicking on [CopilotKit documentation](https://docs.copilotkit.ai/what-is-copilotkit) resulted in a 404 error:
I’ve updated it to the correct URL.

fix: update link in documentation

---

.gitignore
CopilotKit/packages/react-ui/src/components/chat/ChatContext.tsx

This PR introduced further memoization of context items, in order to help prevent, or minimize, some re-renders which are happening one a more advanced use case when customizing the sidebar etc

fix: prevent rerenders by memoizing ui context

---

CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts

The way the type of message chunk is determined when we receive the message stream back, was crooked when the app was deployed and code was minified.
This PR introduced a way of resolving even when the app is minified

fix: change how message chunk type is read

---

CopilotKit/packages/runtime/package.json
CopilotKit/packages/runtime/src/service-adapters/events.ts
CopilotKit/packages/runtime/src/service-adapters/langchain/utils.test.ts
CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts
CopilotKit/pnpm-lock.yaml

When passing parameters for a tool call, it is an option to pass `attributes` for the shape of an object you want the LLM to respond with. It is optional because the LLM can figure the shape on its own if the user wishes.
In this case, the LangChain adapter was failing.
This is the suggested fix

fix: enable dynamic parameters in langchain adapter tool call

---

CopilotKit/examples/next-openai/src/app/components/destination-table.tsx
CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts

Our LangChain adapter was failing to work with a "one at a time" tools. Tools that should be used multiple times with one argument or so.
This PR introduces some changes to make this available, as well as a change to our demo to integrate such action.
This is about the same fix as https://github.com/CopilotKit/CopilotKit/pull/899
but this time, there is no change to the API and how the adapter should be consumed.

fix(langchain-adapter) distinguish between different consecutive calls to the same tool

---

CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts

When setting an array of items as a parameter of an action, the description was not passed to the LLM, leaving it to guess the purpose of the parameter.
This has caused some users to see inconsistent behaviour, as well as the ignoring of instruction prompts set in the description for this kind of parameter type.
In addition, removed 2 variables which were present in the stream resolver of langchain adapter, because these are redundant and could only lead to potential mismatch of values.

fix(langchain-adapter): action descriptions in lc adapter

---

docs/content/docs/(root)/guides/backend-actions/remote-backend-endpoint.mdx

In the onboarding for the execution step for remote backend endpoints had a command that did not work for Poetry. This PR fixes this by adding in tabs reflecting the tabs previously referenced early in the document.

docs(backend-actions): add tabs for FastAPI run step

---

CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts

`remoteActions` definition should still be available after API change. It had an error. This PR provides the fix

fix: fix backwards compatibility for remote actions

---

examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
examples/e2e/tests/coagents-qa-native-demo.spec.ts
examples/e2e/tests/coagents-qa-text-demo.spec.ts
examples/e2e/tests/coagents-routing-demo.spec.ts

Added the option to possibly provide lgc deployment URLs and not override them hardcoded

chore: consider possible js deployment url from main config

---

CopilotKit/packages/runtime/src/lib/runtime/remote-lg-cloud-action.ts
sdk-python/copilotkit/langgraph_agent.py

When calling an LLM before a `copilotkit_emit_state` invocation, it may end up overriding the state we emit manually with said invocation. This PR suggests a fix

fix: fix emitted state being overridden by llm calls

---

.github/workflows/danger.yml
dangerfile.js
package.json
pnpm-lock.yaml

We have 2 different files responsible for executing LangGraph implementation: self hosted in python SDK and a JS execute function on runtime.
These two are currently separate in files and language, but are doing the exact same thing, and we keep them in sync.
This PR adds a "danger" comment that detects if one file has changed but the other remained intact. This is to help developers keep in mind the required sync and alignment between the two files

chore: add danger comment when LG executors are not aligned

---

examples/coagents-research-canvas/ui/src/components/Progress.tsx
examples/e2e/lib/helpers.ts
examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts

Our e2e tests were missing the "emit manual state" for research canvas where searching loading and done states are being emitted manually. This adds test for it

chore(e2e): test streaming of manually emitted state

---

examples/coagents-travel/agent/README.md

Updated README.md, fixes a wrong command to run the server

chore(coagents-travel): wrong command to run the server

---

CopilotKit/packages/runtime/src/agents/langgraph/event-source.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
CopilotKit/packages/runtime/src/lib/telemetry-client.ts
CopilotKit/packages/shared/src/telemetry/events.ts
examples/coagents-ai-researcher/ui/app/api/copilotkit-lgc/route.ts
examples/coagents-qa-native/ui/app/api/copilotkit/route.ts
examples/coagents-qa-text/ui/app/api/copilotkit/route.ts
examples/coagents-research-canvas/ui/pnpm-lock.yaml
examples/coagents-research-canvas/ui/src/app/api/copilotkit/route.ts
examples/coagents-routing/ui/src/app/api/copilotkit/route.ts

LangGraph Cloud has been renamed to LangGraph Platform since we started working on supporting that.
We need to respect the name change while we're still working on this

chore: use the right name for langgraph platform

---

docs/content/docs/(root)/guides/backend-actions/langgraph-platform-endpoint.mdx
docs/content/docs/coagents/quickstart.mdx

The docs work that follows https://github.com/CopilotKit/CopilotKit/pull/1009

docs: rename langgraph cloud into langgraph platform

---

docs/content/docs/coagents/tutorials/ai-travel-app/step-2-langgraph-agent.mdx

This takes the user to the branded page instead of the github now.

docs(travel-tutorial): change link to download LangGraph Studio

---

docs/content/docs/coagents/tutorials/ai-travel-app/step-6-human-in-the-loop.mdx

There was a pretty bad typo in the travel tutorial prompting the user to edit the `trips` node when really they should be editing the `perform_trips_node`.

fix(docs): address a typo related to trips_node in travel tutorial

---

CopilotKit/packages/react-core/src/types/frontend-action.ts

```ts
interface InProgressStateWait<T extends Parameter[] | [] = []> {
status: "inProgress";
args: Partial<MappedParameterTypes<T>>;
/** @deprecated use respond instead */
handler: undefined;
respond: undefined; // missed somehow in earlier change
result: undefined;
}
```

fixes `InProgressStateWait` interface

---

examples/coagents-research-canvas/agent/poetry.lock
examples/coagents-research-canvas/agent/pyproject.toml
examples/coagents-research-canvas/agent/research_canvas/search.py

The following PR overcomes the behaviour of how langgraph emits custom events between asynchronous calls:
https://github.com/CopilotKit/CopilotKit/pull/1063
Having a synchronous call such as using the tavily client (without await. See changes here) is a good way to test this.
This PR utilizes this, so if, at any point, we will run into this again, our e2e testing system should be able to catch it.

chore: adjust demo for langgraph async behavior tests

---

CopilotKit/packages/react-core/src/hooks/use-coagent.ts

Make sure agent state is set immediately to support `setState()` followed by `run()`

Make sure agent state is set immediately

---

docs/content/docs/(root)/guides/backend-actions/langgraph-platform-endpoint.mdx
docs/content/docs/coagents/quickstart.mdx

Highlighting the optional usage of `assistantId` to target an agent

docs(lgc): highlight usage of IDs in agents list

---

docs/content/docs/coagents/quickstart.mdx

Some small changes in the docs in terms of spacing, changing of text (nothing with much meaning for the content)

docs: fix the style of lgc deployment details information

---

CopilotKit/packages/runtime/src/lib/logger.ts

The key changes are:
- Changed "pid" to "*.pid"
- Changed "hostname" to "*.hostname"
The * wildcard ensures the redaction works on these fields regardless of their location in the log object structure. Pino expects paths to be specified in this format to properly identify and redact sensitive information across the entire log object.

fixes paths defined in readact

---

CopilotKit/.changeset/good-eggs-rescue.md
CopilotKit/packages/react-ui/src/components/chat/Input.tsx

When the input field was empty, pressing Enter would still trigger the send() function despite the send button being correctly disabled. Added the sendDisabled check to the onKeyDown handler to ensure consistent validation between button and keyboard triggers.
- Added validation check to Enter key handler
- Ensures empty messages can't be sent via keyboard shortcut
- Makes behavior consistent with disabled send button state
Resolves #1129
- #1129

fix: prevent sending empty messages via Enter key

---

docs/content/docs/coagents/quickstart.mdx

Making sure users know where to import this from in the quickstart

docs(coagents): add import for langGraphPlatformEndpoint quickstart

---

CopilotKit/packages/runtime/src/service-adapters/experimental/empty/empty-adapter.ts
CopilotKit/packages/runtime/src/service-adapters/index.ts

@tylerslaton 
* Implementing Empty Service Adapter (fixes #1157)
* Exporting the adapter for use
* Also exporting the Ollama experimental adapter
* Exporting CopilotRuntimeChatCompletionRequest, CopilotRuntimeChatCompletionResponse to make it easier for someone to implement their own custom adapter
- https://github.com/CopilotKit/CopilotKit/issues/1157

Implementing Empty Service Adapter

---

CopilotKit/packages/react-core/src/components/error-boundary/error-utils.tsx
CopilotKit/packages/react-core/src/components/index.ts
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/Suggestion.tsx

There are many reasons why the abort controller will abort suggestions, or something else.
Most of them are more of a "state" than an error. Therefore, these errors will now be hidden

fix: hide abort controller state error

---

CopilotKit/.changeset/cold-knives-boil.md
CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts

`renderAndWaitForResponse` should run when the status of execution message is "executing". However, in this case, the handler might not be ready yet.
Therefore, this PR waits for it to be ready before rendering

fix: wait for renderAndWaitForResponse handler to be ready before rendering

---

examples/e2e/tests/next-openai.spec.ts

On the basic (non CoAgent) flow, when asking the copilot to make changes, the "state" is changing. We expect that same agent to now be aware of the new state and derive its next actions and knowledge from these.
This PR sets an addition to our e2e tests to verify this

chore: validate core ReAct is aware of latest state

---

CopilotKit/.changeset/fuzzy-crabs-sell.md
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit-props.tsx
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/hooks/index.ts
CopilotKit/packages/react-core/src/hooks/use-copilot-authenticated-action.ts

Adds `useCopilotAuthenticatedAction` hook to handle authentication within chat/conversation. If not authenticated, it renders the `SignInComponent` and allows resuming the previously requested action upon successful sign-in.
> ⚠️ **Important:** This functionality requires a CopilotKit Cloud account. To use these features:
> 1. Sign up at [cloud.copilotkit.ai](https://cloud.copilotkit.ai/)
> 2. Obtain your `publicApiKey` from the dashboard
> 3. Use this key in your CopilotKit provider configuration
Provide `AuthConfig` 
```tsx
/**
* This is an example of how to implement a custom sign-in component.
*/
const authConfig: CopilotKitProps["authConfig"] = {
SignInComponent: ({ onSignInComplete }) => {
/*
sample sign-in service that talks to SSO
*/
const signInService = async (): …
```

feat: adds `useCopilotAuthenticatedAction` hook

---

CopilotKit/.changeset/twenty-dogs-trade.md
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/components/toast/toast-provider.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/hooks/use-coagent-state-render.ts
CopilotKit/packages/react-core/src/hooks/use-coagent.ts
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
CopilotKit/packages/runtime-client-gql/src/graphql/definitions/queries.ts
CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
CopilotKit/packages/runtime/src/graphql/types/agents-response.type.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
docs/content/docs/reference/classes/CopilotRuntime.mdx

We will now show a warning telling the developer that they used an agent we cannot list/find

fix: add warning when using agents that are not available on agent related hooks

---

CopilotKit/.changeset/tender-horses-begin.md
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/Messages.tsx
CopilotKit/packages/react-ui/src/components/chat/Modal.tsx
CopilotKit/packages/react-ui/src/components/chat/index.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/AssistantMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderActionExecutionMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderAgentStateMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderResultMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderTextMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/UserMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/props.ts
docs/content/docs/reference/components/chat/CopilotChat.mdx
docs/content/docs/reference/components/chat/CopilotPopup.mdx
docs/content/docs/reference/components/chat/CopilotSidebar.mdx

This PR adds a collection of new interfaces that allow the user to easily add their own custom message components. These interfaces are:
- `AssistantMessage`
- `UserMessage`
These each take their own props that will be used within CopilotKit to communicate state back to the user defined properties.
For example, a user could add their own custom loading bar like so.
```tsx
import { AssistantMessageProps, CopilotSidebar, Markdown } from "@copilotkit/react-ui";
const AssistantMessage = (props: AssistantMessageProps) => {
const { message, isLoading, isGenerating, component } = props;
return (
<div>
{ message && 
<div className="copilotKitMessage copilotKitAssistantMessage !max-w-full">
<Markdown content={message || ""} />
</div>
}
{component}
{(isLoading || isGenerating) && 
<div …
```

feat(react-ui): add interfaces for full message customization

---

CopilotKit/.changeset/eighty-geese-lay.md
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts

If someone is quick to type and send before suggestions are shown, we abort fetching suggestions. As a natural behaviour of abort controller, an error it thrown when the fetch is aborted.
This PR will silence these errors

fix: silence abort controller cancellation throwing an error

---

examples/coagents-travel/agent/travel/chat.py
examples/coagents-travel/agent/travel/trips.py

Improving the cancel UX and also fixing an issue related to state not being persisted once an operation occurs.

fix(coagents-travel): fix issues around cancelling UX

---

CopilotKit/packages/react-ui/src/components/chat/messages/RenderActionExecutionMessage.tsx

Small UI improvement for when the `render` method of an action returns an error. This error is shown in the chat and should look more like a chat bubble than what it is today

fix: improve UI for error message showing when action render has error

---

CopilotKit/.changeset/mean-peas-repair.md
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/service-adapters/empty/empty-adapter.ts
CopilotKit/packages/runtime/src/service-adapters/index.ts
docs/components/react/multi-provider-content/utils.ts

rename ExperimentalEmptyAdapter to EmptyAdapter
backwards compatible

fix: rename ExperimentalEmptyAdapter to EmptyAdapter

---

CopilotKit/.changeset/sixty-lizards-smile.md
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-core/src/components/error-boundary/error-utils.tsx
CopilotKit/packages/react-ui/src/components/chat/Suggestion.tsx
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts
CopilotKit/packages/shared/package.json
CopilotKit/packages/shared/src/utils/errors.ts
CopilotKit/packages/shared/src/utils/index.ts
CopilotKit/pnpm-lock.yaml
docs/content/docs/(root)/meta.json
docs/content/docs/(root)/troubleshooting/common-issues.mdx
docs/content/docs/coagents/troubleshooting/common-issues.mdx
examples/e2e/lib/helpers.ts
examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts

Currently error handling is done "ad-hoc". It means that we're throwing generic errors around, catching and handling. Logging (to console, to a logging solution etc) is also done next to each error.
We do not distinguish between low level errors, server errors or others.
This PR aims to bring a change to that
This PR introduces the concept of custom made error classes. These classes are made to describe a broad, or a specific error we expect.
Using of custom classes means we're moving error handling from "the outside" (next to where the error happens, e.g in `catch` block) to "the inside", which means inside a class.
When an error class is created, we are able to perform operations, or better describe the issue. Not all these concepts are already part of this PR, but the latter is. A …

fix: better error messages

---

CONTRIBUTING.md

fix docs link
fix the documentation link in contributing.md

docs: fix docs link in contributing.md

---

CopilotKit/packages/react-ui/src/hooks/use-copilot-chat-suggestions.tsx
docs/content/docs/reference/hooks/useCopilotChatSuggestions.mdx

Adding a new `available` prop which will allow a user to conditionally enabled or disable a specific chat suggestion.

feat(use-copilot-chat-suggestions): add available prop

---

CopilotKit/.changeset/long-poets-relax.md
CopilotKit/packages/react-ui/src/components/dev-console/utils.ts

This PR sets the "check for updates" endpoint to point to production.

fix(react-ui): check for updates endpoint to point to production

---

CopilotKit/.changeset/seven-hats-attack.md
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
docs/content/docs/reference/classes/CopilotRuntime.mdx

We have several fetch calls, depending on the context and what needs fetching.
They are handling errors with our new error classes, but for abort signal errors, we have a centralized location where we handle this, so I am allowing the error to pass through "as is", so that handler handles it

fix: allow abort errors to pass further down to handler

---

CopilotKit/.changeset/tricky-pots-notice.md
CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts

LangSmith API key is not required to run langgraph agents. Therefore, making it optional

fix: allow empty langsmith api key

---

CopilotKit/.changeset/silent-terms-float.md
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts

Adds the option to pass authorization tokens from the frontend by adding them to the `properties` property of `copilotRuntimeNextJSAppRouterEndpoint` and the `CopilotKit` components in the frontend. The LangGraph Client was previously being constructed without the option to pass auth headers, making it impossible to use the next custom auth workflow with [LangGraph platform](https://langchain-ai.github.io/langgraph/how-tos/auth/custom_auth/)
This is more of a hotfix, since the graphql properties object was the only convenient way to transfer auth headers all the way down the call stack to where the LangGraph Platform Clients were being constructed.
Note: the more consistent way to pass these auth tokens is by accessing the cookies in browser. CopilotKit seems to call `/assistants/search` …

fix: pass additional context to the langgraph state

---

examples/coagents-ai-researcher/agent/pyproject.toml
examples/coagents-qa-native/agent/pyproject.toml
examples/coagents-qa-text/agent/pyproject.toml
examples/coagents-routing/agent/pyproject.toml
examples/coagents-travel/agent/pyproject.toml

These dependencies as an array is what picked up by Langgraph platform when running an agent container, so they should be available

chore: add dependencies array to fix langgraph platform deployments

---

CopilotKit/.changeset/cool-spoons-cough.md
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts

Fixing an issue where we were not closing the controller on abort error suppression. This would result in "Stop generation" hanging as soon as it was clicked.

fix(runtime-client-gql): call controller.close() after suppressing abort errors

---

examples/coagents-qa-native/agent/email_agent/agent.py

Safely retrieve the values CPK actions, this ensures that this will run even outside of a CopilotKit env.

fix(coagents-qa-native): safely retrieve cpk actions, allowing for LangGraph Studio to execute

---

docs/app/not-found.tsx
docs/content/docs/coagents/quickstart/langgraph.mdx

Fixing a typo that broke smart tabs in the quickstart and adding a better 404 page.

fix(docs): address typo and add better 404 page

---

examples/coagents-qa-native/agent-js/langgraph.json

chore: fix coagents qa native deployment by getting latest corepack

chore: fix coagents qa native deployment by getting latest corepack

---

examples/coagents-qa-text/agent-js/langgraph.json
examples/coagents-research-canvas/agent-js/langgraph.json
examples/coagents-routing/agent-js/langgraph.json

chore: fix coagents deployment by getting latest corepack

chore: fix coagents deployment by getting latest corepack

---

CopilotKit/.changeset/cyan-vans-begin.md
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts

There is a more accurate way to get current running node name. Fixes a situation in which wrong node name would result in not executing node interrupt flows properly

fix: use langgraph metadata to get node name

---

CopilotKit/.changeset/seven-fishes-hide.md
CopilotKit/packages/react-core/src/hooks/use-copilot-runtime-client.ts
CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
CopilotKit/packages/shared/src/utils/errors.ts

If an error occurs, we will check and show a version mismatch error. Otherwise we will just show a warning (on dev only ofc)

fix: use warning when version mismatch is not expected to error out

---

CopilotKit/packages/react-core/src/hooks/use-chat.ts
CopilotKit/packages/react-ui/src/components/chat/Input.tsx

When using simple interrupt, no messages should be allowed to be sent. This is because the agent is on a full stop and should not invoke the graph without response to the interrupt. Otherwise, unexpected things will happen

fix(interrupt): disable input when interrupt is active

---

CopilotKit/.changeset/chilled-dolphins-jog.md
CopilotKit/packages/shared/src/utils/errors.ts

For some reason, the following merged PR was gone from main:
https://github.com/CopilotKit/CopilotKit/pull/1367
This brings it back

fix(errors): fix internal usage of error resolver

---

CopilotKit/.changeset/chilly-rats-bow.md
CopilotKit/packages/react-core/src/hooks/use-langgraph-interrupt.ts
CopilotKit/packages/react-core/src/types/interrupt-action.ts
CopilotKit/packages/runtime-client-gql/src/client/types.ts
CopilotKit/packages/runtime-client-gql/src/index.ts

This PR adds the ability to set the type of the interrupt event, so developers using `useLangGraphInterrupt` are able to have type safety when using that value

fix: provide the ability to type interrupt event value

---

sdk-python/copilotkit/langgraph_agent.py

Running async savers (like AsyncPostgresSaver) requires that CPK uses langgraph's async interface when setting/getting state etc.

fix: enable usage of async savers by using lg async interface

---

sdk-python/pyproject.toml

chore: release python sdk v0.1.39

---

CopilotKit/.changeset/sharp-bikes-develop.md
CopilotKit/packages/react-core/src/hooks/use-langgraph-interrupt-render.ts
CopilotKit/packages/react-core/src/hooks/use-langgraph-interrupt.ts
CopilotKit/packages/react-core/src/types/interrupt-action.ts
docs/content/docs/reference/hooks/meta.json
docs/content/docs/reference/hooks/useLangGraphInterrupt.mdx
examples/coagents-qa-native/ui/app/Mailer.tsx

Simplifying the conditions to render an interrupt using the hook.
Instead of a "filters" array, we will now use a simple method that returns a boolean.

fix: simplify lg interrupt conditions

---

examples/coagents-shared-state/agent/pyproject.toml
examples/coagents-starter/agent-py/pyproject.toml
examples/coagents-wait-user-input/agent/pyproject.toml

A dependency array is required to make a project deployable on langgraph cloud. Therefore, these were added where needed

chore: add missing dependency arrays to demos

---

docs/content/docs/coagents/quickstart/langgraph.mdx

Adding a link to make sure users know where to get their public API key.

docs(coagents): add a link to copilot cloud in the coagents quickstart

---

CopilotKit/.changeset/dirty-scissors-wash.md
CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
CopilotKit/packages/runtime/src/service-adapters/conversion.ts
CopilotKit/packages/shared/src/utils/index.ts

We would like to consider, on some cases, that items which error out on one of their properties (for example) should not be a part of the end result of a mapped list.
Therefore, introducing `tryMap` method and its usage

fix: use tryMap method to filter out possibly invalid items

---

examples/Dockerfile.agent-python

ChromaDB (required by CrewAI) fails to initialize due to outdated SQLite version in the base Python image.
- Added SQLite 3.45.0 installation from source in the Python agent Dockerfile
- Configured with default settings and cleaned up build artifacts
- Maintains existing Poetry and dependency installation flow

fix: upgrade sqlite3 for ChromaDB compatibility

---

examples/Dockerfile.agent-python

- Add multi-stage build to compile SQLite 3.45.0 from source
- Rebuild Python 3.12 against new SQLite with --with-system-sqlite3
- Set LD_LIBRARY_PATH to ensure proper library loading
- Fix ChromaDB initialization error requiring SQLite >= 3.35.0

fix: rebuild Python with SQLite 3.45.0 for ChromaDB compatibility

---

CopilotKit/.changeset/heavy-owls-relax.md
CopilotKit/packages/react-core/src/hooks/use-coagent.ts

This PR internally improves the stability and predictability of functions that depends on state or a bound-to-change variables inside the `useCoAgent` implementation

fix: use memoization in useCoAgent internal functions

---

CopilotKit/.changeset/calm-carpets-peel.md
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
docs/content/docs/coagents/shared-state/meta.json
docs/content/docs/coagents/shared-state/state-filtering.mdx
docs/content/docs/coagents/shared-state/state-inputs-outputs.mdx
sdk-python/copilotkit/langgraph_agent.py

This PR bring support for [input and output schema by langgraph](https://langchain-ai.github.io/langgraph/how-tos/input_output_schema/).
It does so by breaking down the possible state schema keys of start and end nodes, and only allowing the keys in these schemas in the state emitted.
This is because in general, streaming does not support this feature out of the box (while "invoke" does)

feat: support input and output schema of langgraph

---

CopilotKit/.changeset/large-flowers-double.md
CopilotKit/packages/runtime/src/agents/langgraph/event-source.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts

When setting a backend action in runtime setup (on route.ts for example), and when this action is passed to an agent (as opposed to none CoAgent flow), the action handler would in fact not run.
This PR fixes this issue

fix(runtime): fix execution of runtime set backend action handlers

---

CopilotKit/.changeset/chilled-hairs-wait.md
CopilotKit/packages/runtime/src/agents/langgraph/event-source.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
docs/content/docs/reference/classes/CopilotRuntime.mdx

Disabling the actions that are set as BE actions when creating a new runtime instance, if there are agents.
This is because agents have their own tools

fix: disable runtime actions on agent

---

docs/content/docs/(root)/guides/custom-look-and-feel/bring-your-own-components.mdx
docs/content/docs/(root)/guides/custom-look-and-feel/customize-built-in-ui-components.mdx

Updating the Custom Components section to be Custom Sub-components instead

docs(customize-ui): add sub-components section

---

CopilotKit/.changeset/calm-carpets-peel.md
CopilotKit/.changeset/chilled-hairs-wait.md
CopilotKit/.changeset/chilly-rats-bow.md
CopilotKit/.changeset/dirty-scissors-wash.md
CopilotKit/.changeset/fair-papayas-breathe.md
CopilotKit/.changeset/healthy-foxes-serve.md
CopilotKit/.changeset/heavy-owls-relax.md
CopilotKit/.changeset/hot-turtles-fold.md
CopilotKit/.changeset/large-flowers-double.md
CopilotKit/.changeset/polite-falcons-melt.md
CopilotKit/.changeset/pre.json
CopilotKit/.changeset/proud-dingos-poke.md
CopilotKit/.changeset/sharp-bikes-develop.md
CopilotKit/.changeset/ten-mangos-sort.md
CopilotKit/.changeset/tiny-donkeys-speak.md
CopilotKit/packages/react-core/CHANGELOG.md
CopilotKit/packages/react-core/package.json
CopilotKit/packages/react-textarea/CHANGELOG.md
CopilotKit/packages/react-textarea/package.json
CopilotKit/packages/react-ui/CHANGELOG.md
CopilotKit/packages/react-ui/package.json
CopilotKit/packages/runtime-client-gql/CHANGELOG.md
CopilotKit/packages/runtime-client-gql/package.json
CopilotKit/packages/runtime/CHANGELOG.md
CopilotKit/packages/runtime/package.json
CopilotKit/packages/sdk-js/CHANGELOG.md
CopilotKit/packages/sdk-js/package.json
CopilotKit/packages/shared/CHANGELOG.md
CopilotKit/packages/shared/package.json

Release workflow failed on cleanup/restoration step after releasing a new NPM version. This PR sets everything manually

chore: set post release changeset values

---

examples/copilot-form-filling/README.md

Now that we have this example deployed in vercel, I'm adding in a link

chore(copilot-form-filling): add link to vercel hosted example

---

docs/content/docs/(root)/cookbook/state-machine.mdx

Fixing some broken links in the state machine cookbook

fix: address typos due to new path for state-machine

---

CopilotKit/examples/node-express/package.json
CopilotKit/examples/node-express/src/index.ts
CopilotKit/examples/node-http/package.json
CopilotKit/examples/node-http/src/index.ts

When the express server and node HTTP server are used as runtime when using environment variables. It fails to get the environment variables from the .env files, so for that, I added the import for the dotenv package, configured it, and added dotenv in the package.json file for both  node-express and  Node-HTTP

Added dotenv Imports in node-express and node-http

---

CopilotKit/scripts/docs/lib/files.ts
docs/content/docs/reference/sdk/python/CrewAI.mdx
docs/content/docs/reference/sdk/python/CrewAIAgent.mdx

- Fix documentation generation for CrewAI SDK and agent files. The docs generator was failing during commits because it was looking for Python files in incorrect locations. This PR:
Updates the path for crewai_agent.py to point to its correct location in the crewai subdirectory
- Adds a configuration entry for crewai_sdk.py to document the CrewAI SDK functions
These changes prevent the "ENOENT: no such file or directory" errors that were occurring during pre-commit hooks when running the documentation generator.
N/A

fixes docs generation 

---

CopilotKit/packages/runtime-client-gql/src/client/conversion.ts

revert PR that accidentally got into main

Revert "use `parseJson` util to safely parse"

---

CopilotKit/.changeset/olive-brooms-switch.md
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts

Putting back the runtime actions when remote endpoints are present.

fix: re-enable runtime actions when remote endpoint is set

---

CopilotKit/.changeset/fast-books-talk.md
CopilotKit/packages/react-core/src/types/index.ts

Exports missing action-related types from the react-core package's public API, including `ActionRenderPropsNoArgsWait`, `ActionRenderPropsNoArgs`, `ActionRenderPropsWait`, `FrontendAction`, `FrontendActionAvailability`, and `CatchAllFrontendAction`. This fixes the "Module has no exported member" TypeScript errors when trying to use these types.
- N/A

fix(react-core): export missing action-related types for public API

---

docs/content/docs/coagents/shared-state/state-inputs-outputs.mdx

This PR further expends the "input output schema" documentation code example, so it's easier to "reproduce" this and see it working

docs: enhance input output schema example

---

CopilotKit/.changeset/rich-tomatoes-dress.md
CopilotKit/packages/react-ui/src/css/input.css

set text area within the input box to transparent background

fix: set text area within the input box to transparent background

---

CopilotKit/.changeset/twenty-houses-end.md
CopilotKit/packages/react-ui/src/css/colors.css

When using OS dark theme but app system has light theme set up, the embedded copilotkit chat uses dark theme.
This PR makes the app theme prevail the system theme.

fix: adjust order of colors so app themes prevails OS theme

---

examples/Dockerfile.agent-js
examples/coagents-qa-native/agent-js/src/agent.ts
examples/coagents-qa-text/agent-js/src/agent.ts
examples/coagents-research-canvas/agent-js/src/agent.ts
examples/coagents-routing/agent-js/src/agent.ts

- Removes MemorySaver from agent.ts since Lambda functions are stateless
- Keeps /tmp/.langgraph_api directory as writable space for temporary files
- Fixes EROFS (read-only filesystem) errors when running in Lambda
The agent doesn't need to persist state between invocations since each Lambda 
execution is independent. This change removes the persistence layer while 
maintaining a writable temporary directory for other potential LangGraph needs.

fix: remove LangGraph persistence in Lambda agent

---

docs/content/docs/(root)/guides/connect-your-data/backend.mdx
docs/content/docs/(root)/tutorials/ai-todo-app/step-4-copilot-actions.mdx

This PR introduces minor changes to two links provided in the documentation
1. on connecting your data to backend guide, backend actions link was incorrect
2. on todos app tutorial, for usecopilatactions further reference link was incorrect as well
Finally, a little grammar fix on connecting your data to backend was made as well.

fix(docs): fixed broken links put as reference

---

CopilotKit/.changeset/mean-crabs-enjoy.md
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/shared/src/utils/errors.ts
docs/content/docs/coagents/troubleshooting/common-issues.mdx

Seeing how "langgraph platform" endpoints concept may confuse some folks, this PR adds more error messages if the endpoint types are misused, as well with an accompanying troubleshooting url

fix: clarify difference between lgp endpoints to fastapi endpoints

---

CopilotKit/.changeset/tiny-comics-study.md
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts

In order to enable input/output schemas of langgraph, we fetch the schema for a given langgraph graph when running it.
The schema returned from this fetching has changed unexpectedly, flagging the fact that lack of schema/faulty schema is not something CPK can recover from. This PR provides recovery

fix: handle failure to fetch langgraph schema

---

docs/content/docs/coagents/meta.json
docs/content/docs/crewai-crews/meta.json
docs/content/docs/crewai-flows/meta.json

Adding a link to the framework appropriate demo viewer into the docs' sidebar

feat: add demo viewer to coagents docs

---

CopilotKit/.changeset/rude-insects-grab.md
CopilotKit/packages/react-ui/src/css/console.css

We removed the support which follows operation system theme, but this was forgotten. Following.

fix: remove styles corresponding to OS dark theme

---

CopilotKit/.changeset/stupid-walls-smash.md
CopilotKit/packages/react-ui/src/components/chat/Input.tsx

The new input has a far bigger box, which can be seen as divided into 2 rows: 1 is the textarea, the 2nd is the buttons.
When this PR is merged, whenever a user clicks on the 2nd row (buttons) but NOT ON A BUTTON, the text area will be focused, thus making the "Hit box" of the text area far larger and easier to target

fix: focus on text area when clicking in input box

---

CopilotKit/.changeset/metal-actors-double.md
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
docs/content/docs/coagents/advanced/adding-runtime-configuration.mdx
sdk-python/copilotkit/langgraph_agent.py
sdk-python/copilotkit/utils.py

This PR adds support to "ConfigurableSchema" - the schema of "configurable" of langgraph.
What this means is that configuration passed that does not adhere to the schema, is being filtered out
See more: https://langchain-ai.github.io/langgraph/how-tos/configuration/#configure-the-graph

feat: add support for langgraph config schema

---

CopilotKit/.changeset/ten-doors-grow.md
CopilotKit/packages/react-core/src/hooks/use-chat.ts
CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderTextMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/props.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
docs/content/docs/reference/components/chat/CopilotChat.mdx
docs/content/docs/reference/components/chat/CopilotPopup.mdx
docs/content/docs/reference/components/chat/CopilotSidebar.mdx
sdk-python/copilotkit/langgraph_agent.py

Fixes bug in which regeneration of messages on langgraph ends up with the old message, doubled.
It also alters the FE behaviour of the regenerate button: When clicking, all messages after and including the message to be deleted, are removed.

fix: fix duplicate messages on regenerate

---

CopilotKit/.changeset/moody-countries-clean.md
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit-props.tsx
CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
CopilotKit/packages/react-core/src/context/copilot-context.tsx
CopilotKit/packages/react-core/src/hooks/use-chat.ts
CopilotKit/packages/runtime/src/lib/index.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/mcp-tools-utils.ts
docs/content/docs/reference/classes/CopilotRuntime.mdx
docs/content/docs/reference/components/CopilotKit.mdx

Integrates support for discovering and using tools from external servers adhering to the Model Context Protocol.
- Adds `mcpEndpoints` and `createMCPClient` options to `CopilotKit` props and `CopilotRuntime` constructor parameters.
- The `mcpEndpoints` array configures connections to MCP servers.
- The `createMCPClient` function (required when using `mcpEndpoints`) allows users to inject their specific MCP client implementation (e.g., using `@anthropic-ai/sdk`, `ai/experimental`) into the runtime.
- Defines `MCPTool` and `MCPClient` interfaces for abstraction.
- Implements utility functions (`extractParametersFromSchema`, `convertMCPToolsToActions`) to convert MCP tools into standard CopilotKit actions.
- Modifies `CopilotRuntime` to:
- Lazily initialize MCP clients using the provided …

feat: Add Model Context Protocol (MCP) support

---

docs/content/docs/crewai-flows/persistence/loading-message-history.mdx
examples/coagents-starter-crewai-flows/agent-py/sample_agent/agent.py
examples/coagents-starter-crewai-flows/agent-py/sample_agent/demo.py
examples/coagents-starter-crewai-flows/ui/app/layout.tsx
sdk-python/copilotkit/crewai/crewai_agent.py

When resuming a persisted flow, the agent now retrieves messages from the
stored state and converts them to CopilotKit format. This allows for proper
continuation of conversations across sessions.
- Added conversion of stored messages using crewai_flow_messages_to_copilotkit
- Improved error handling with detailed log messages
- Used existing logger from crewai_sdk module

fix(crewai): Retrieve and convert messages from stored state

---

sdk-python/pyproject.toml

Release fixes to HITL interrupt on python sdk

chore: release python 0.1.44

---

.github/workflows/preview-envs-deploy.yml

It appears that GitHub’s caching service is now enforcing stricter validation, causing 422 errors on Node jobs. Removing the caching configuration resolves the issue, ensuring that our CI pipeline runs without interruption. We can revisit caching strategies once the underlying issue is addressed.

fix: remove caching from preview setup-node to avoid 422 errors

---

CopilotKit/.changeset/afraid-gorillas-mate.md
CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
CopilotKit/packages/react-ui/src/components/chat/ChatContext.tsx
CopilotKit/packages/react-ui/src/components/chat/Icons.tsx
CopilotKit/packages/react-ui/src/components/chat/ImageUploadQueue.tsx
CopilotKit/packages/react-ui/src/components/chat/Input.tsx
CopilotKit/packages/react-ui/src/components/chat/Messages.tsx
CopilotKit/packages/react-ui/src/components/chat/index.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/RenderImageMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/messages/UserMessage.tsx
CopilotKit/packages/react-ui/src/components/chat/props.ts
CopilotKit/packages/runtime-client-gql/src/client/conversion.ts
CopilotKit/packages/runtime-client-gql/src/client/types.ts
CopilotKit/packages/runtime-client-gql/src/graphql/definitions/mutations.ts
CopilotKit/packages/runtime/src/graphql/inputs/message.input.ts
CopilotKit/packages/runtime/src/graphql/types/converted/index.ts
CopilotKit/packages/runtime/src/graphql/types/copilot-response.type.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
CopilotKit/packages/runtime/src/service-adapters/anthropic/utils.ts
CopilotKit/packages/runtime/src/service-adapters/conversion.ts
CopilotKit/packages/runtime/src/service-adapters/openai/utils.ts
docs/content/docs/reference/components/chat/CopilotChat.mdx
docs/content/docs/reference/components/chat/CopilotPopup.mdx
docs/content/docs/reference/components/chat/CopilotSidebar.mdx

Adds support for image inputs across multiple AI models including Claude and OpenAI. This PR:
- Implements image upload functionality in the user interface
- Adds clipboard pasting support for images
- Allows users to add images during loading states
- Updates service adapters for OpenAI and Anthropic to handle image content
- Improves UX by immediately clearing images after submission
- Updates documentation to reflect multi-model image support
- Adds content-type property for proper handling of image data
Special thanks to @mnutt (Michael Nutt) for implementing this valuable feature that significantly enhances our multi-modal capabilities!
Same as #1680 

 feat: add image input support with multi-model compatibility, pasting, and UX improvements

---

CopilotKit/packages/shared/src/telemetry/telemetry-client.ts

PostHog was underreporting traffic due to sampled telemetry. We now include `sampleWeight = 1 / sampleRate` in global event properties to allow proper scaling using sum(sampleWeight). This eliminates the need for formula-based charts.

fix(telemetry): add sampleWeight to support accurate volume estimation in PostHog

---

CopilotKit/.changeset/khaki-candles-compete.md
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/mcp-tools-utils.ts

Fixes a TypeScript error in the MCP tool schema structure by correctly nesting the `properties` and `required` fields inside a `parameters` object to match the expected interface. This resolves the error: "Type '{ properties: any; required: any; } | {}' is not assignable to type '{ parameters?: { properties?: Record<string, any>; required?: string[]; jsonSchema?: Record<string, any>; }; }'".
- N/A

Fix MCP tool schema structure to match interface requirements

---

docs/content/docs/coagents/quickstart/langgraph.mdx
docs/content/docs/crewai-crews/quickstart/crewai.mdx
docs/content/docs/crewai-flows/quickstart/crewai.mdx

The CLI has been tested for a bit, now its time to integrate into the documentation. This adds CLI paths into both LangGraph and Flows.

feat(docs): add CLI as default path in the documentation

---

CopilotKit/.changeset/cuddly-llamas-grin.md
CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts

Fixes the error that is shown when attempting to hash langsmith api key that doesn't exist

fix: langsmith key hashing

---

CopilotKit/.changeset/poor-garlics-melt.md
CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
CopilotKit/packages/runtime/src/lib/runtime/agui-action.ts
CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts

As we slowly move towards greater AGUI support and a complete LangGraph AGUI agent, this PR makes small adjustments to how we read and report interrupts when consuming AGUI agents

fix: prepare cpk agui wiring for ag-ui langgraph support

---

sdk-python/pyproject.toml

Releasing python 0.1.53 which supports all langgraph versions up to 0.5.0 + includes some fixes which will support the usage of 0.5.0

chore: release python sdk version 0.1.53
