CopilotKit/CopilotKit

- CopilotKit/examples/next-openai/src/app/components/vacation-notes.tsx
- CopilotKit/examples/next-openai/src/app/textarea/page.tsx
- CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/use-add-branding-css.tsx
- CopilotKit/packages/react-textarea/src/components/copilot-textarea/copilot-textarea.tsx
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-autosuggestions-function.tsx
- CopilotKit/packages/react-textarea/src/lib/slatejs-edits/replace-text.ts
- CopilotKit/packages/react-textarea/src/types/base/base-autosuggestions-config.tsx
- CopilotKit/packages/react-textarea/src/types/base/base-copilot-textarea-props.tsx
- CopilotKit/packages/react-textarea/src/types/standard-autosuggestions/autosuggestions-config.tsx
also: minor branding css bugfix attempt
> Textarea: remove default apiEndpoint, rename purposePrompt to textarePurpose

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/base-copilot-textarea.tsx
- CopilotKit/packages/react-textarea/src/components/hovering-toolbar/hovering-toolbar.tsx
- CopilotKit/packages/react-textarea/src/types/base/base-copilot-textarea-props.tsx
added support for hover menu customization via `hoverMenuClassname` argument on textarea props
> textarea hoverMenuClassname

- CopilotKit/packages/react-textarea/src/components/hovering-toolbar/text-insertion-prompt-box/included-files-preview.tsx
> fix(textarea): use the document picture in the preview component

- docs/contribute/quickstart-contribute.mdx
- docs/getting-started/development.mdx
- docs/getting-started/quickstart-backend.mdx
- docs/mint.json
> getting started contributing guide

- README.md
clearer high level description
> Update README.md - overview

- CopilotKit/packages/react-core/src/index.tsx
- CopilotKit/packages/react-core/src/openai/chat-completion-client.ts
- CopilotKit/packages/react-core/src/openai/chat-completion-stream.ts
- CopilotKit/packages/react-core/src/openai/chat-completion-transport.ts
- CopilotKit/packages/react-core/src/openai/index.tsx
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-autosuggestions-function.tsx
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-insertion-function.tsx
- CopilotKit/pnpm-lock.yaml
- WIP.md
This makes the textarea work with the vercel ai replacement.
- Introduces a new class `ChatCompletionStream` for simple, text only responses in the form of `ReadableStream<string>`
- Rename the low level http parsing class to `ChatCompletionTransport` for clarity
- `useMakeStandardAutosuggestionFunction` and `useMakeStandardInsertionOrEditingFunction` have been adapted to make use of this
@ataibarkai please test, for me the textarea demo was working, but I am not sure how to test  useMakeStandardInsertionOrEditingFunction
> Fix textarea

- docs/getting-started/quickstart-backend.mdx
- docs/getting-started/quickstart-chatbot.mdx
- docs/getting-started/quickstart-textarea.mdx
quickstart update for 'ai' package dependency removal
> docs update

- CopilotKit/.changeset/honest-colts-judge.md
- CopilotKit/.changeset/large-spoons-burn.md
- CopilotKit/.changeset/pre.json
- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/node/CHANGELOG.md
- CopilotKit/examples/node/package.json
- CopilotKit/packages/backend/CHANGELOG.md
- CopilotKit/packages/backend/package.json
- CopilotKit/packages/backend/src/lib/openai-adapter.ts
- CopilotKit/packages/eslint-config-custom/CHANGELOG.md
- CopilotKit/packages/eslint-config-custom/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/packages/tailwind-config/CHANGELOG.md
- CopilotKit/packages/tailwind-config/package.json
- CopilotKit/packages/tsconfig/CHANGELOG.md
- CopilotKit/packages/tsconfig/package.json
- Add openai instance getter to OpenAIAdapter
```
const openaiAdapter = new OpenAIAdapter()
const openaiInstance = openaiAdapter.openai
```
cc @arnoldmukisa https://discord.com/channels/1122926057641742418/1205139676378435695/1209734819463036988
> Add openai instance getter to OpenAIAdapter

- CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
- CopilotKit/packages/react-ui/src/components/chat/Input.tsx
- CopilotKit/packages/react-ui/src/components/chat/props.ts
> focus when copilot becomes visible

- README.md
> Update README.md - new high level updates

- CopilotKit/.changeset/calm-crews-tickle.md
- CopilotKit/.changeset/itchy-laws-hang.md
- CopilotKit/.changeset/pre.json
- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/node/CHANGELOG.md
- CopilotKit/examples/node/package.json
- CopilotKit/packages/backend/CHANGELOG.md
- CopilotKit/packages/backend/package.json
- CopilotKit/packages/backend/src/lib/copilotkit-backend-implementation.ts
- CopilotKit/packages/backend/src/lib/copilotkit-backend.ts
- CopilotKit/packages/eslint-config-custom/CHANGELOG.md
- CopilotKit/packages/eslint-config-custom/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-core/src/hooks/use-copilot-action-implementation.ts
- CopilotKit/packages/react-core/src/hooks/use-make-copilot-actionable.ts
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/packages/shared/src/utils/annotated-function.ts
- CopilotKit/packages/tailwind-config/CHANGELOG.md
- CopilotKit/packages/tailwind-config/package.json
- CopilotKit/packages/tsconfig/CHANGELOG.md
- CopilotKit/packages/tsconfig/package.json
Support the deprecated AnnotatedFunction in CopilotBackend to ensure backward compatibility.
> Support deprecated AnnotatedFunction in CopilotBackend

- docs/contribute/quickstart-contribute.mdx
Update contributor docs to say <CopilotKit Directory> instead of [root]
> Contributor feedback: [root] is confusing

- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-openai/src/app/presentation/actions/useAppendSlide.tsx
- CopilotKit/examples/next-openai/src/app/presentation/actions/useUpdateSlide.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/ActionButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/AddSlideButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/DeleteSlideButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/GenerateSlideButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/NavButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/PerformResearchSwitch.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/buttons/SpeakCurrentSlideButton.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/main/Header.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/main/Presentation.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/main/Slide.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/misc/SlideNumberIndicator.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/misc/SlidePreview.tsx
- CopilotKit/examples/next-openai/src/app/presentation/page.tsx
- CopilotKit/examples/next-openai/src/app/presentation/styles.css
- CopilotKit/examples/next-openai/src/app/presentation/types.ts
- CopilotKit/examples/next-openai/src/app/presentation/utils/globalAudio.tsx
- CopilotKit/pnpm-lock.yaml
Updates the presentation demo to the latest version found at https://github.com/CopilotKit/presentation-demo
> update presentation demo

- CopilotKit/examples/next-openai/src/app/presentation/page.tsx
- CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
- CopilotKit/packages/react-ui/src/components/chat/ChatContext.tsx
- CopilotKit/packages/react-ui/src/components/chat/Popup.tsx
- CopilotKit/packages/react-ui/src/components/chat/Sidebar.tsx
- CopilotKit/packages/react-ui/src/components/chat/index.tsx
This adds the `open` property to the chat context, as well as the function `setOpen` to control opening/closing the chat.
> add open/setOpen to chat context

- CopilotKit/examples/next-openai/src/app/components/Presentation.tsx
- CopilotKit/examples/next-openai/src/app/components/destination-row.tsx
- CopilotKit/examples/next-openai/src/app/components/destination-table.tsx
- CopilotKit/examples/next-openai/src/app/presentation/components/main/Presentation.tsx
- CopilotKit/examples/next-openai/src/app/textarea/page.tsx
- CopilotKit/packages/react-core/src/hooks/index.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-readable.ts
- CopilotKit/packages/react-core/src/hooks/use-make-copilot-readable.ts
- CopilotKit/packages/react-core/src/lib/copilot-task.ts
- CopilotKit/scripts/qa/lib/firebase/page.tsx
- CopilotKit/scripts/qa/lib/langserve/next/page.tsx
- CopilotKit/scripts/qa/lib/next/page.tsx
- CopilotKit/scripts/qa/lib/node/page.tsx
- CopilotKit/scripts/qa/lib/upgrade/page.tsx
- README.md
Implements `useCopilotReadable`:
- keyword args
- automatic serialization
- custom conversion function
- custom dependencies
> implement useCopilotReadable

- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit-props.tsx
- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
- CopilotKit/packages/react-core/src/context/copilot-context.tsx
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-action-implementation.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts
- CopilotKit/packages/react-core/src/hooks/use-flat-category-store.ts
- CopilotKit/packages/react-core/src/hooks/use-make-copilot-actionable.ts
- CopilotKit/packages/react-core/src/hooks/use-make-copilot-document-readable.ts
- CopilotKit/packages/react-core/src/hooks/use-make-copilot-readable.ts
- CopilotKit/packages/react-core/src/hooks/use-tree.ts
- CopilotKit/packages/react-core/src/index.tsx
- CopilotKit/packages/react-core/src/openai-assistants/hooks/use-assistants.ts
This PR brings significant enhancements to the messaging capabilities within the CopilotKit, improving both the internal message handling mechanisms and the API surfaces related to messaging. Here are the key changes introduced:
**Introduction of Message Handling in Context and Hooks:**
A series of new hooks and context methods (addMessageContext, getMessagesContext, messageContext, messagesContext) have been introduced. These allow for more flexible and efficient management of message data across different components and layers of the application.
Extended Functionalities in useTree and useFlatCategoryStore Hooks:
Both hooks now support message-oriented actions, enabling the addition and retrieval of message data tied to specific threads or identifiers. This is particularly useful for …
> Enhanced Messaging Capabilities in CopilotKit

- CopilotKit/package.json
- CopilotKit/pnpm-lock.yaml
- docs/contribute/quickstart-contribute.mdx
See: https://github.com/CopilotKit/CopilotKit/issues/334
> Update pnpm version

- docs/favicon.svg
- docs/mint.json
* Adjust colors
* Apply favicon
> feat(docs): apply copilotkit brand

- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit-props.tsx
- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
- CopilotKit/packages/react-core/src/context/copilot-context.tsx
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/lib/copilot-task.ts
- CopilotKit/packages/react-core/src/utils/extract.ts
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-autosuggestions-function.tsx
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-insertion-function.tsx
- CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
- CopilotKit/packages/runtime/src/lib/copilot-runtime.ts
- CopilotKit/packages/runtime/src/service-adapters/experimental/groq/groq-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/experimental/ollama/ollama-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/google/google-genai-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/langchain/langchain-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-assistant-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/service-adapter.ts
- docs/_snippets/style.css
- docs/reference/classes/CopilotRuntime.mdx
- docs/reference/classes/GoogleGenerativeAIAdapter.mdx
- docs/reference/classes/LangChainAdapter.mdx
- docs/reference/classes/OpenAIAdapter.mdx
- docs/reference/classes/OpenAIAssistantAdapter.mdx
- docs/reference/components/CopilotKit.mdx
- docs/reference/components/CopilotTextarea.mdx
- Support custom props that are passed to the runtime.
- Support before and after req middleware
- Fix docs
> Support for custom props and middleware

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- Add README.md and homepage/url to published packages
> Release v1.0.2

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- Include @copilotkit/runtime-client-gql NPM package version in request to Runtime
> Release v1.0.5

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- Add _copilotkit internal properties to runtime
> Release v1.0.7

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- Remove redundant console logs
> Release v1.0.8

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
- Official support for Groq (`GroqAdapter`)
> Release v1.1.0

- docs/globals.css
- docs/pages/[...rest].tsx
- Redirect all 404s to homepage
- Fix styling on mobile
> fox(docs): 404 and styling issues

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
> Release v1.1.2

- CopilotKit/.vscode/cspell.json
- CopilotKit/packages/shared/package.json
- CopilotKit/packages/shared/src/utils/random-id.ts
- CopilotKit/pnpm-lock.yaml
use uuid package instead of globalThis.crypto
> Fix crypto import errors

- CopilotKit/packages/react-ui/package.json
- CopilotKit/pnpm-lock.yaml
Unpin headless UI and update to latest version
> Unpin headless UI

- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts
- CopilotKit/packages/react-core/src/lib/copilot-task.ts
- CopilotKit/packages/react-core/src/types/frontend-action.ts
- CopilotKit/packages/react-core/src/utils/extract.ts
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-autosuggestions-function.tsx
- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-insertion-function.tsx
- CopilotKit/packages/runtime/src/graphql/inputs/frontend.input.ts
- CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
- CopilotKit/packages/runtime/src/lib/copilot-runtime.ts
- docs/pages/reference/hooks/useCopilotAction.mdx
Select available frontend/backend 
- frontend: Actions take an optional `disabled` property
- backend: The middleware is passed the current frontend url
> Select actions

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
> Release v1.3.1

- demos/CONTRIBUTING.md
- demos/List.md
- demos/README.md
- demos/TEMPLATE.md
The `demos` folder provides detailed instructions and guidelines to help Hacktoberfest participants successfully submit their projects.
> Added the Hacktoberfest folder called demos containing a README.md  & TEMPLATE.md

- README.md
"autocompeltions" should be "autocompletions".
> fixed the typo here in readme 

- community/demos/snippy.md
fixes: #637 
This PR adds a new feature to the project: a Code Snippet Generator that suggests code snippets based on user prompts for various programming languages. This feature leverages CopilotKit as a core component and uses Shadcn-UI for styling all UI elements. The implementation follows the requirements outlined in the Hacktoberfest event.
Adds Code Snippet Generator functionality.
Integrates CopilotKit for generating relevant code snippets from prompts.
Styles all UI components using Shadcn-UI, ensuring consistency with the design guidelines.
> fix(demo): code snippet generator using copilotkit

- SECURITY.md
I had added the SECURITY.md file
> Added SECURITY.md File #660

- README.md
Hello! I have updated the README.md file and fixed some typos and also improved visibility of certain sections. Thank you very much!
> Updated README.md and fixed typos

- CODE_OF_CONDUCT.md
> feat: created CODE_OF_CONDUCT.md

- CopilotKit/packages/react-core/src/hooks/use-coagent.ts
When running an agent, allow the developer to specify the hint to the LLM by using a function instead of automatically appending a message.
> Allow specifying the hint as a function

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
Add followUp property to useCopilotAction
> Release 1.3.4

- docs/content/docs/(root)/quickstart.mdx
- docs/snippets/self-hosting-copilot-runtime-create-endpoint.mdx
- Rename `llmAdapter` to `serviceAdapter`
- Add `npm install openai` to install the OpenAI SDK
> fix(docs): quickstart errors

- README.md
Adding our new "banking-demo" to the readme.
The banking app demonstrates a few core CopilotKit features such as actions and readables. Some of them are cross pages, as well as suggestions, generative UI and more.
> chore(demo): add banking app demo to the readme

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
> release 1.3.5

- README.md
fix link title for the new banking demo in readme
> fix: fix link title for the new banking demo in readme

- examples/coagents-research-canvas/ui/package.json
- examples/coagents-research-canvas/ui/pnpm-lock.yaml
Make the canvas demo work by using a pre-release
> use pre-release in canvas demo

- CopilotKit/packages/runtime/src/agents/langgraph/event-source.ts
- CopilotKit/packages/runtime/src/agents/langgraph/events.ts
Filter empty messages & fix an issue where text messages from Anthropic are sent as array instead of a string
> filter empty messages when using Anthropic

- CopilotKit/packages/react-ui/src/hooks/use-copilot-chat-suggestions.tsx
Fix a bug where suggestions don't update
> make sure suggestions reload and update when dependencies change

- docs/content/docs/coagents/advanced/copilotkit-state.mdx
- docs/content/docs/coagents/advanced/meta.json
Document `CopilotKitState` and show how to use it
> document `CopilotKitState`

- examples/coagents-qa-native/ui/app/api/copilotkit/route.ts
- examples/coagents-qa-text/ui/app/api/copilotkit/route.ts
- examples/coagents-qa/ui/app/api/copilotkit/route.ts
- examples/coagents-shared-state/ui/app/api/copilotkit/route.ts
- examples/coagents-starter/ui/app/api/copilotkit/route.ts
- examples/coagents-wait-user-input/ui/app/api/copilotkit/route.ts
Dynamic `process.env.REMOTE_ACTION_URL` support for CoAgents examples.
> feat(examples): dynamic remote action urls for coagent examples

- community/demos/priority-todolist.md
In this project, I developed a TO-DO List with Prioritization based on deadline or importance using React for the frontend, Tailwind CSS for styling, and Shadcn UI for enhanced UI components.
> Priority TO-DO list

- community/demos/task-manager.md
1. Adding a new demo application in the community/demos directory
2. This project is a task manager app that leverages copilotkit to help users add, edit, update, and manage tasks efficiently,
> demo: Add Task Manager (Hacktoberfest Demo) 

- community/content/README.md
fixes some minor typos and a non functional embedded link in README.md
> minor fixes in README.md

- community/demos/study-sphere.md
Adds a demo Study Sphere - https://github.com/kom-senapati/study-sphere/
> DEMO App: Study Sphere

- community/demos/study-buddy.md
> ⭐ 22 - Study Buddy (Hacktoberfest Demo) #634

- community/demos/Recipe_Generator.md
In this project, I developed a Recipe Generator and Suggestion App using React for the frontend, Tailwind CSS for styling, and Shadcn UI for enhanced UI components.
> Added Recipe Generator

- community/demos/summarify.md
Summarify is a content summary tool which leverages the Hooks provided by CopilotKit to enable users summerize their contents in varied tones.
It also leverages copilotActions to generate a UI based on LLMs response.
[Live Demo](https://summarify-puce.vercel.app/)
- Summarify:
- Suggestions
> ⭐ 27 - Content Summary Tool (Hacktoberfest Demo) - Summarify

- community/demos/movie-suggestion-bot.md
Adds a demo project - movie-suggestion-bot
> ⭐ 18 - Movie Suggestion Bot (Hacktoberfest Demo) #630

- community/demos/meal-prep-planner.md
- A meal prep planning web app with an AI powered chatbot built with Copilotkit.
- [✓] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [✓] If the PR changes or adds functionality, I have updated the relevant documentation
> demo: Add meal prep planner demo

- community/demos/mini-faq-bot.md
- A demo web app with an AI powered FAQ chatbot built with Copilotkit.
- [✓] I have read the Contribution Guide
- [✓] If the PR changes or adds functionality, I have updated the relevant documentation
> feat: Submit hacktoberfest demo

- community/demos/cal-buddy.md
Added my project, Cal Buddy, in community demos.
> Added community demo: Cal Buddy

- community/demos/music-lyric-finder.md
- A music lyric finder web app powered by Copilotkit.
> demo: Add Music Lyric Finder demo

- community/demos/snippetsorcerer.md
> fix: #678-demo

- community/demos/copilotkit-browser-extension.md
- A browser extension featuring copilotkit.
> 🌐 demo: browser extension featuring copilotkit

- community/demos/snippy.md
Fixed images and added youtube and x refs to the demo
- This PR fixes the images which were missing from #637
> fix: demo files

- community/demos/EventTimer.md
In this project, I developed an Event Countdown Timer with Copilot Bot integration using React for the frontend, Tailwind CSS for styling, and the CopilotKit for interactive guidance and suggestions.
- Event Timer: Users can add an event with a specific target date and time. The app displays a countdown for the event, and users can manage multiple events by adding or removing them from the list.
- Copilot Bot Integration: The app is integrated with Copilot Bot to assist users with instructions on how to set timers, offering help for timer creation in a user-friendly way.
List the technologies and frameworks you used (e.g., CopilotKit, Next.js)
- [Next.js](https://nextjs.org)
- [Tailwind CSS](https://tailwindcss.com)
- [CopilotKit](https://copilotkit.ai) …
> demo: Add Event Timer Bot (Hacktoberfest Demo) 

- docs/content/docs/(root)/(other)/contributing/code-contributions/index.mdx
- docs/content/docs/(root)/guides/custom-look-and-feel/customize-built-in-ui-components.mdx
- docs/content/docs/(root)/quickstart.mdx
- docs/content/docs/(root)/tutorials/ai-powered-textarea/step-3-copilot-textarea.mdx
- docs/content/docs/(root)/tutorials/ai-powered-textarea/step-4-copilot-readable-state.mdx
- docs/content/docs/(root)/tutorials/ai-todo-app/next-steps.mdx
- docs/content/docs/(root)/tutorials/ai-todo-app/step-2-setup-copilotkit.mdx
- docs/content/docs/coagents/advanced/intermediate-state-streaming.mdx
- docs/content/docs/coagents/chat-ui/hitl/text-hitl.mdx
This PR fixes typos on the official documentation site of CopiloKit. Find the list of the pages modified below.
N/A
> docs: Fix typos on certain pages of CopilotKit Docs Site

- examples/coagents-research-canvas/readme.md
hey @mme, i was going through the repo. and found a typo error. so fixed the typo in ```readme.md``` file.
-  not any specific.
> fixed: typo in ```CopilotKit/examples/coagents-research-canvas/readme.md```

- community/demos/legal-document-reviewer.md
Adds Legal document reviewer tool demo
> Create Legal Document Reviewer Demo

- community/demos/code-snippet-generator.md
https://github.com/CopilotKit/CopilotKit/issues/678
> Steph code snippet gen

- community/demos/news-aggregator.md
I added all the required details for my completed project, a news aggregator as requested in one of the created issue
- [X ] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [ X] If the PR changes or adds functionality, I have updated the relevant documentation
> completed readme.md

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
Fix libraries for Next.js 15 / React 19 support.
> Release v1.3.7

- community/demos/github-pull-request-tracker.md
Added demo of GitHub pull requested tracker that is using copilotkit
NA
> demo: AI powered GitHub Pull Request Tracker

- community/demos/anshuman-language-translator.md
Adds a demo for Language Translator - https://github.com/anshuman-rai-27/lang-translator-ai
> Demo anshuman-language-translator.md

- community/demos/expense-tracker.md
I made an expense tracker demo for hacktoberfest
> feat: add expense tracker demo

- .github/ISSUE_TEMPLATE/issue_template.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR fixes a few typos in the following GitHub templates.
- Pull Request Template
- Issue Template
N/A
> fix: Updated typos in GitHub templates

- community/demos/mayank-mohapatra-language-translator.md
What does this PR do?
Adds a demo for Language Translator - https://github.com/Mayank77maruti/TranslateApp
Related PRs and Issues
(Direct link to related PR or issue, if relevant)
Links
[Live Demo](https://translate-app-kappa-six.vercel.app/)
[Tweet Link](https://x.com/MayankMoha31086/status/1849896925413376098)
Checklist
I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
If the PR changes or adds functionality, I have updated the relevant documentation
> Language Tranlator added

- community/demos/mayank-receipe-generator.md
[Link](https://receipe-generator-1zyq.vercel.app/)
[dev to](https://dev.to/mayank_mohapatra/recipe-generator-powered-by-copilotkit-chatbot-1mlg)
> receipe generator added

- community/demos/Flashcards_Quiz_ai.md
[Live Link](https://ai-flashcards-free.vercel.app/)
- ⭐ 17 - Interactive Flashcards (Hacktoberfest Demo) #629
> Added Interactive Flashcards and Quiz Generator

- community/demos/Recipe-Modifier.md
This tool can modify recipes to be vegetarian, non-vegetarian, or even tailored for a healthy diet. Enter your recipe, select a modification, and get instant suggestions! 
Github link :  https://github.com/anshuman-rai-27/Recipe_Modifier
Live demo : https://recipe-modifier.vercel.app/
> demo:recipe-modifier added (Hacktoberfest Demo) 

- community/demos/movie-bot.md
1.Adding a new demo application in the community/demos directory
2.This project is a Movie recommendation Bot that leverages copilot kit to help users get suggestion of movies based on their genre, mood and previous watch history.
> demo: Add Movie recommendation Bot (Hacktoberfest Demo)

- community/demos/emotion-reads.md
Created a Readme file in the demo folder describing about the project built by me, for the issue  #610 .
Project Name: Emotion Reads
Project Description: Recommends books based on the emotions described by the person.
[Issue #610 ](https://github.com/CopilotKit/CopilotKit/issues/610)
> Demo: Emotion Reads

- community/demos/priyanshu-new-aggregrator.md
[Live Link](https://copilot-news.vercel.app/)
[dev to](https://dev.to/priyanshudas01/building-an-ai-powered-news-search-dashboard-with-copilotkit-2gna)
> Demo: ai news aggregator 

- community/demos/mayank_news_generator.md
[Live Link](https://news-pulse-new-i2od.vercel.app/)
[dev to](https://dev.to/mayank_mohapatra/how-i-built-news-pulse-with-copilotkit-5c3p)
> news aggregrator added

- community/demos/priyanshu-language-translator.md
Adds a demo for Language Translator 
Live link: https://language-copilot.vercel.app/
Github :  https://github.com/PriyanshuDas01/Language_Copilot
> Demo: Language translator

- community/demos/anshuman-recipe-modifier.md
This tool can modify recipes to be vegetarian, non-vegetarian, or even tailored for a healthy diet. Enter your recipe, select a modification, and get instant suggestions!
Github link : https://github.com/anshuman-rai-27/Recipe_Modifier
Live demo : https://recipe-modifier.vercel.app/
> Demo recipe-modifier

- community/demos/cookbook.md
This PR adds a new demo to the project: a Recipe Generator, that generates recipes based on user prompts for various ingredients and dishes. This project leverages CopilotKit as a core component and uses Shadcn-UI for styling all UI elements. The implementation follows the requirements outlined in the Hacktoberfest event.
- fixes: #603
> demo: create cookbook

- community/demos/music_lyrics_finder.md
- Music lyrics finder with beautiful UI powered by AI
> 🎵 demo: AI powered MUSIC lyrics fetcher/finder!

- community/demos/quizflip.md
**Description:**
QuizFlip is an app that generates flashcards on any topic you ask for, helping users learn and review efficiently. It integrates with CopilotKit to generate flashcards and quizzes quickly and accurately.
> 17 - Interactive Flashcards (Hacktoberfest Demo) #629

- CopilotKit/packages/react-textarea/src/hooks/make-autosuggestions-function/use-make-standard-autosuggestions-function.tsx
- CopilotKit/packages/react-textarea/src/types/autosuggestions-config/suggestions-api-config.tsx
- CopilotKit/packages/runtime/src/service-adapters/anthropic/anthropic-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts
Gemini and Anthropic were only partially working in auto-suggestions (text area). This PR suggests fixes in few different areas:
1. The default Anthropic model that was use produces unexpected results. Replaced with one which will yield better results.
2. The signature of returned value is not always as expected. The necessary changes were made in order to accommodate the different possibilities
> fix: Fix non autosuggestion when used with Gemini & Anthropic

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
> release v1.3.8

- docs/components/react/coagents/coagents-enterprise-cta.tsx
> Changed the CTA button directing from the webinar to the video

- community/demos/financial-tracker.md
A demo for financial adviser with copilotkit
[(https://github.com/TRIPLE-ADE/copilotkit-financial-adviser/blob/main/public/Screenshot.png](https://github.com/TRIPLE-ADE/copilotkit-financial-adviser/blob/main/public/Screenshot.png))
> feat: Personal Finance Advice Bot

- community/demos/Meditation Companion.md
This PR introduces a Meditation Companion App that allows users to explore daily meditation prompts, with features like a real-time clock display, interactive UI elements, and prompt generation.
> Hacktoberfest Demo: Mindfulness Meditation Companion

- community/demos/daily-quote-app.md
Just added the bonus section in my md file.
> feat: Added bonus section in md file

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
> release 1.3.10

- CopilotKit/.changeset/lazy-books-trade.md
- CopilotKit/.changeset/pre.json
- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
Fix duplicate messages caused by using the wrong ID
> Fix duplicate messages

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
Release 1.3.12 which contains LangChain adapter fixes
> Release 1.3.12

- CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/base-copilot-textarea.tsx
- CopilotKit/packages/react-textarea/src/components/base-copilot-textarea/render-element.tsx
- CopilotKit/packages/react-textarea/src/components/hovering-toolbar/hovering-toolbar-components.tsx
- CopilotKit/packages/react-textarea/src/components/hovering-toolbar/hovering-toolbar.tsx
- CopilotKit/packages/react-textarea/src/components/hovering-toolbar/text-insertion-prompt-box/hovering-insertion-prompt-box-core.tsx
- CopilotKit/packages/react-ui/src/components/chat/Input.tsx
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderActionExecutionMessage.tsx
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderTextMessage.tsx
> feat: data test ids

- .dockerignore
- examples/coagents-ai-researcher/agent/Dockerfile
- examples/coagents-qa-native/agent/Dockerfile
- examples/coagents-qa-text/agent/Dockerfile
- examples/coagents-research-canvas/agent/Dockerfile
- infra/bin/infra.ts
- infra/lib/coagents-demo-stack.ts
> chore(previews): use local python sdk

- CopilotKit/packages/react-ui/src/components/chat/Suggestion.tsx
Fixes an error when the suggestion instructions were too long. Instead of passing it as tool description, we now pass it as a system message.
> Fix an error when the suggestion instructions are too long

- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- examples/coagents-routing/ui/src/app/components/ui/select.tsx
Update the running status return from`useCoAgent`)
> Make sure the CoAgent running property is updated

- docs/content/docs/reference/components/CopilotTextarea.mdx
- docs/content/docs/reference/components/chat/CopilotChat.mdx
- docs/content/docs/reference/components/chat/CopilotPopup.mdx
- docs/content/docs/reference/components/chat/CopilotSidebar.mdx
- docs/content/docs/reference/components/chat/index.mdx
- docs/package-lock.json
> fix-4 urls and1 text mistake resolve

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
- docs/content/docs/reference/components/CopilotTextarea.mdx
- docs/content/docs/reference/components/chat/CopilotChat.mdx
- docs/content/docs/reference/components/chat/CopilotPopup.mdx
- docs/content/docs/reference/components/chat/CopilotSidebar.mdx
> Release 1.3.15

- CopilotKit/packages/react-textarea/src/components/copilot-textarea/copilot-textarea.tsx
- CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
- CopilotKit/packages/react-ui/src/components/chat/Popup.tsx
- CopilotKit/packages/react-ui/src/components/chat/Sidebar.tsx
- CopilotKit/scripts/docs/lib/reference-doc.ts
- docs/content/docs/reference/classes/CopilotRuntime.mdx
- docs/content/docs/reference/classes/CopilotTask.mdx
- docs/content/docs/reference/classes/llm-adapters/AnthropicAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/GoogleGenerativeAIAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/GroqAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/LangChainAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/OpenAIAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/OpenAIAssistantAdapter.mdx
- docs/content/docs/reference/components/CopilotKit.mdx
- docs/content/docs/reference/components/CopilotTextarea.mdx
- docs/content/docs/reference/components/chat/CopilotChat.mdx
- docs/content/docs/reference/components/chat/CopilotPopup.mdx
- docs/content/docs/reference/components/chat/CopilotSidebar.mdx
- docs/content/docs/reference/hooks/useCopilotChat.mdx
- docs/content/docs/reference/hooks/useCopilotChatSuggestions.mdx
- docs/content/docs/reference/hooks/useCopilotReadable.mdx
- docs/next-env.d.ts
add DO NOT MODIFY note for autogenerated reference docs, pointing the correct file to modify.
> chore(docs): add DO NOT MODIFY note for autogenerated reference docs

- CopilotKit/scripts/qa/lib/langserve/app/server.py
- docs/content/docs/coagents/advanced/using-google-gemini.mdx
- docs/content/docs/coagents/getting-started.mdx
- examples/coagents-ai-researcher/agent/ai_researcher/demo.py
- examples/coagents-qa-native/agent/my_agent/demo.py
- examples/coagents-qa-text/agent/my_agent/demo.py
- examples/coagents-qa/agent/my_agent/demo.py
- examples/coagents-research-canvas/agent/research_canvas/demo.py
- examples/coagents-routing/agent/my_agent/demo.py
- examples/coagents-shared-state/agent/my_agent/demo.py
- examples/coagents-starter/agent/my_agent/demo.py
- examples/coagents-wait-user-input/agent/my_agent/demo.py
- sdk-python/copilotkit/demos/ai_researcher/demo.py
- sdk-python/copilotkit/demos/autotale_ai/demo.py
- sdk-python/copilotkit/demos/multi_agent/demo.py
- sdk-python/copilotkit/demos/multi_agent_anthropic/demo.py
- sdk-python/copilotkit/demos/qa/demo.py
- sdk-python/copilotkit/demos/research_canvas/demo.py
- sdk-python/copilotkit/demos/starter/demo.py
- sdk-python/copilotkit/demos/wait_user_input/demo.py
rename LangGraphAgent.agent -> graph in all demos / docs
> rename LangGraphAgent.agent -> graph

- .gitignore
- examples/e2e/README.md
- examples/e2e/package.json
This PR sets up the initial test infrastructure using Playwright Test framework. Specifically, it:
- Initializes the project with necessary Playwright dependencies
- Adds convenient npm scripts for running different types of tests
- Includes a browser installation setup script
- Provides documentation in README.md for getting started
- N/A (Initial setup PR)
- Added detailed README.md with setup instructions
- Included all available test scripts and their usage
- Provided troubleshooting guide and additional resources
> chore: initial Playwright test setup with documentation

- .github/workflows/preview-envs-deploy.yml
- examples/coagents-routing/agent/my_agent/demo.py
- examples/coagents-routing/agent/my_agent/model.py
- examples/coagents-routing/ui/.gitignore
- examples/coagents-routing/ui/next.config.mjs
- infra/bin/infra.ts
* Remove Perplexity clone
* Add CoAgents Routing
> feat(demos): add coagents-routing to preview envs setup, remove perplexity clone

- CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
- docs/content/docs/reference/classes/llm-adapters/OpenAIAdapter.mdx
> Add Azure OpenAI docs

- docs/content/docs/(root)/index.mdx
- docs/pnpm-lock.yaml
> docs: updated landing page

- docs/content/docs/(root)/index.mdx
- docs/pnpm-lock.yaml
Reverts CopilotKit/CopilotKit#944
> Revert "docs: updated landing page"

- .github/ISSUE_TEMPLATE/1-bug-report.yml
Fixed a typo in the bug report template description
#946
> fix: correct typo in bug report template description

- examples/e2e/README.md
- examples/e2e/playwright.config.ts
- examples/e2e/reporters/structured-reporter.ts
- examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
- examples/e2e/tsconfig.json
Added test coverage for additional AI models in the Canvas Researcher demo E2E tests:
- Added test for Anthropic model integration
- Added test for Google Generative AI model integration
Changed:
```diff
const models = [
{ name: "OpenAI", value: "openai" },
+ { name: "Anthropic", value: "anthropic"},
+ { name: "Google Generative AI", value: "google_genai"}
]
> chore: run tests against all models

- examples/e2e/lib/variants.ts
- examples/e2e/reporters/structured-reporter.ts
- examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
Enhances the Playwright test reporter to group results by variants, providing better visibility into test outcomes across different test configurations:
1. Modified the test reporter data structure to include variant grouping
2. Updated result collection to track test outcomes per variant
3. Enhanced report formatting to display results organized by variants
```markdown
Status: failed
Duration: 186.6s
chromium → 0/3 ✅ passed • 3 ❌ failed
chromium → 0/3 ✅ passed • 3 ❌ failed
```
Key changes:
- Added variant extraction utility: `extractVariant()`
- Modified reporter data structure to include variant level grouping
- Updated result collection in `onTestEnd` to track variant-specific outcomes
- Enhanced report generation to display results by variant
- Added proper type definitions for …
> add variant

- examples/coagents-routing/ui/src/app/page.tsx
- examples/e2e/tests/coagents-routing-demo.spec.ts
Add tests for the coagents-routing demo
> feat(e2e): add tests for coagents routing demo

- examples/e2e/lib/variants.ts
- examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
- examples/e2e/tests/coagents-routing-demo.spec.ts
Gemini seems broken. Disabling it for now until it's fixed.
> chore(e2e): disable google variant for tests

- examples/e2e/tests/coagents-qa-text-demo.spec.ts
> feat(e2e): add tests for coagents qa text demo

- .github/workflows/e2e.yml
- .github/workflows/preview-envs-deploy.yml
- examples/e2e/package.json
- examples/e2e/pnpm-lock.yaml
- examples/e2e/reporters/structured-reporter.ts
- infra/generate-table.js
> enhance report

- examples/coagents-travel/README.md
Had a typo in the header for the CoAgents Travel example.
> fix(coagents-travel): CoAgents Starter => CoAgents Travel

- examples/coagents-research-canvas/ui/src/components/ResearchCanvas.tsx
This PR fixes an issue where the ResearchCanvas component had the container property applied. As such, its size was bound to the screen size. This was not aligned at larger screen sizes which causes a gap between the ResearchCanvas and CopilotChat.
> fix(coagents-research-canvas): remove container property for Research Canvas

- .github/workflows/e2e.yml
- CopilotKit/examples/next-openai/src/app/components/ServiceAdapterSelector.tsx
- CopilotKit/examples/next-openai/src/app/page.tsx
- CopilotKit/examples/next-openai/src/app/presentation/page.tsx
- CopilotKit/examples/next-openai/src/app/textarea/page.tsx
- CopilotKit/examples/next-openai/src/app/travel/page.tsx
- CopilotKit/packages/runtime-client-gql/tsup.config.bundled_0x2kmnt4uwn.mjs
- CopilotKit/packages/runtime-client-gql/tsup.config.bundled_qpx2b969p4.mjs
- examples/e2e/.gitignore
- examples/e2e/package.json
- examples/e2e/pnpm-lock.yaml
- examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
- examples/e2e/tests/next-openai.spec.ts
Add support for Cloud endpoint + public API key for preview envs
> feat(next-openai): add cloud support for preview envs

- .github/workflows/e2e.yml
- examples/e2e/playwright.config.ts
- examples/e2e/reporters/structured-reporter.ts
- examples/e2e/tests/coagents-qa-text-demo.spec.ts
Fixes test result counting in the StructuredReporter to accurately report failed tests.
N/A
> fixes test reporter

- examples/coagents-research-canvas/agent/research_canvas/search.py
Switch to AsyncTavilyClient to work around issues with emitting state when using the sync version
> switch to async tavily client

- examples/coagents-travel/ui/app/layout.tsx
- examples/coagents-travel/ui/app/page.tsx
- examples/coagents-travel/ui/tailwind.config.ts
Fixing a build issue from Vercel, they just wanted me to use their Script component instead of the standard HTML tag.
> fix(coagents-travel): use Script component for leafletjs

- examples/coagents-travel/ui/app/globals.css
- examples/coagents-travel/ui/app/page.tsx
- examples/coagents-travel/ui/components/AddPlace.tsx
- examples/coagents-travel/ui/components/MapCanvas.tsx
- examples/coagents-travel/ui/components/MobileTripCard.tsx
- examples/coagents-travel/ui/components/PlaceCard.tsx
- examples/coagents-travel/ui/components/PlaceForMap.tsx
- examples/coagents-travel/ui/components/TripCard.tsx
- examples/coagents-travel/ui/components/TripContent.tsx
- examples/coagents-travel/ui/components/ui/drawer.tsx
- examples/coagents-travel/ui/lib/hooks/use-media-query.tsx
- examples/coagents-travel/ui/package.json
- examples/coagents-travel/ui/pnpm-lock.yaml
Adds mobile styling for the travel application
> feat(coagents-travel): add styling for mobile

- CopilotKit/packages/runtime/src/service-adapters/anthropic/anthropic-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/google/google-genai-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/groq/groq-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/langchain/langchain-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-assistant-adapter.ts
- docs/content/docs/reference/classes/llm-adapters/AnthropicAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/GoogleGenerativeAIAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/GroqAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/LangChainAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/OpenAIAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/OpenAIAssistantAdapter.mdx
This PR rewrites the reference for several LLM adapters we offer
> docs: remove outdated streamHttpServerResponse call from adapter docs

- examples/coagents-travel/ui/app/globals.css
- examples/coagents-travel/ui/app/page.tsx
- examples/coagents-travel/ui/components/MapCanvas.tsx
Previously the application looked a little weird in an iframe. As such I improve the tablet styling to activate sooner and for the open state of the copilot to respond to screen width.
> style(coagents-travel): add better mobile styling for scaling in iframes

- docs/content/docs/coagents/tutorials/ai-travel-app/step-1-checkout-repo.mdx
Updating the wording of step 1 in the travel tutorial to be clearer
> docs(travel-tutorial): add clearer setup step

- examples/coagents-research-canvas/agent-js/package.json
- examples/coagents-research-canvas/agent-js/pnpm-lock.yaml
> fix version of sdk-js in research-canvas app

- CopilotKit/examples/next-openai/src/app/api/copilotkit/route.ts
- CopilotKit/examples/next-openai/src/app/components/vacation-list.tsx
- examples/coagents-qa-native/ui/app/Mailer.tsx
- examples/coagents-qa-text/ui/app/Greeter.tsx
- examples/coagents-research-canvas/ui/src/app/Main.tsx
- examples/e2e/lib/config-helper.ts
- examples/e2e/tests/next-openai.spec.ts
> adds more functionality to example apps

- CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts
- CopilotKit/packages/react-core/src/types/frontend-action.ts
- docs/content/docs/(root)/guides/generative-ui.mdx
- docs/content/docs/coagents/chat-ui/hitl/json-hitl.mdx
- docs/content/docs/reference/hooks/useCopilotAction.mdx
Renames renderAndWait prop to renderAndWaitForResponse and its associated handler parameter to respond for better clarity and API consistency.
> [CPK-850] changes renderAndWait interface

- CopilotKit/packages/react-core/src/types/frontend-action.ts
> fixes deprecation typo

- docs/app/(home)/layout.tsx
- docs/components/react/coagents/coagents-enterprise-cta.tsx
- docs/components/react/subdocs-menu.tsx
- docs/content/docs/coagents/advanced/meta.json
- docs/content/docs/coagents/chat-ui/meta.json
- docs/content/docs/coagents/index.mdx
- docs/content/docs/coagents/meta.json
- docs/content/docs/coagents/react-ui/meta.json
- docs/content/docs/coagents/videos/meta.json
- docs/content/docs/coagents/videos/perplexity-clone.mdx
- docs/content/docs/coagents/videos/research-canvas.mdx
Changing up things in the docs for better visiblity!
> docs: change layout and components for better visiblity

- examples/coagents-travel/ui/app/page.tsx
> fixes `runtimeUrl`  in coagent-travel demo

- docs/components/layout/top-bar.tsx
- docs/components/react/socials.tsx
The style for the social and feedback buttons was a little too distracting so I'm muting it a bit.
> style(docs): add more muted feedback button

- CopilotKit/packages/react-core/src/hooks/use-coagent-state-render.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts
- CopilotKit/packages/react-core/src/lib/copilot-task.ts
- CopilotKit/packages/react-ui/src/components/chat/Popup.tsx
- CopilotKit/packages/react-ui/src/components/chat/Sidebar.tsx
- docs/content/docs/(root)/tutorials/ai-powered-textarea/next-steps.mdx
- docs/content/docs/coagents/concepts/agentic-copilots.mdx
- docs/content/docs/coagents/index.mdx
- docs/content/docs/coagents/tutorials/ai-travel-app/step-4-integrate-the-agent.mdx
- docs/content/docs/reference/classes/CopilotTask.mdx
- docs/content/docs/reference/components/chat/CopilotPopup.mdx
- docs/content/docs/reference/components/chat/CopilotSidebar.mdx
- docs/content/docs/reference/hooks/useCoAgentStateRender.mdx
- docs/content/docs/reference/hooks/useCopilotAction.mdx
A change of the docs resulted in some broken links.
This PR fixes all the broken links and direct to the right places
> docs: fix broken links

- CopilotKit/packages/shared/src/constants/index.ts
> fixes the api url 

- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/pnpm-lock.yaml
- docs/content/docs/(root)/quickstart.mdx
Fixes issues with the quickstart:
- move the dependency on `@copilotkit/runtime` to `devDependencies` since its only needed during build time
- explicitly install runtime in docs
- Remove this: import `"@copilotkit/react-textarea/styles.css";` we don't use it in the quickstart
- Fix install: `npm install @copilotkit/react-ui @copilotkit/runtime`
> Fix issues with the quickstart

- .github/workflows/e2e.yml
- examples/e2e/reporters/structured-reporter.ts
> test result status report fix

- docs/content/docs/coagents/quickstart.mdx
- docs/snippets/langgraph-platform-deployment-tabs.mdx
- examples/coagents-travel/agent/poetry.lock
- examples/coagents-travel/agent/pyproject.toml
> [CPK-918] updates instructions for langgraph.js

- CopilotKit/packages/react-ui/src/components/dev-console/console.tsx
- CopilotKit/packages/react-ui/src/components/help-modal/icons.tsx
- CopilotKit/packages/react-ui/src/components/help-modal/index.tsx
- CopilotKit/packages/react-ui/src/components/help-modal/modal.tsx
This PR adds a help button to our dev console, so users are redirected to get help if needed
> feat: dev console help

- CopilotKit/packages/react-ui/src/css/markdown.css
Fixes the CSS of the assistant message when not using tailwind or other CSS resets
> fix assistant message css when not using tailwind

- docs/content/docs/(root)/tutorials/ai-powered-textarea/step-2-setup-copilotkit.mdx
- docs/content/docs/(root)/tutorials/ai-todo-app/step-2-setup-copilotkit.mdx
- docs/content/docs/coagents/tutorials/ai-travel-app/step-3-setup-copilotkit.mdx
- docs/snippets/copilot-cloud-configure-copilotkit-provider.mdx
update todo tutorial, fixing cloud setup and CSS issue
> update todo tutorial, fixing cloud setup and CSS issue

- docs/content/docs/coagents/chat-ui/hitl/json-hitl.mdx
Adding JSON HITL fix that show-cases how it doesn't have to just be a string that is sent.
> fix(docs): add actual JSON to JSON HITL documentation

- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-coagent.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
- examples/coagents-routing/ui/src/app/page.tsx
support running an agent without messages
> support running an agent without messages

- docs/content/docs/coagents/tutorials/ai-travel-app/overview.mdx
Adding the video we recorded for the travel tutorial to the docs!
> docs: add travel tutorial video

- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/sdk-js/CHANGELOG.md
- CopilotKit/packages/sdk-js/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
- Make sure agent state is set immediately (#1077)
- Support running an agent without messages (#1075)
> Release v1.4.2

- sdk-python/copilotkit/langchain.py
Changing the sleep time added in this PR https://github.com/CopilotKit/CopilotKit/pull/1063
> fix: increase time of waiting on async force fix

- docs/content/docs/coagents/quickstart.mdx
remove leftover of google gemini workaround
> docs: remove leftover of google gemini workaround

- CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
- CopilotKit/packages/shared/src/telemetry/events.ts
This PR introduces a bit clearer error surfacing, as an effort to give better information to developers using CoAgents
> fix: log more errors and track errors on telemetry

- CopilotKit/.changeset/light-kangaroos-brush.md
- CopilotKit/.changeset/pre.json
- CopilotKit/examples/next-openai/CHANGELOG.md
- CopilotKit/examples/next-openai/package.json
- CopilotKit/examples/next-pages-router/CHANGELOG.md
- CopilotKit/examples/next-pages-router/package.json
- CopilotKit/examples/node-express/CHANGELOG.md
- CopilotKit/examples/node-express/package.json
- CopilotKit/examples/node-http/CHANGELOG.md
- CopilotKit/examples/node-http/package.json
- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/sdk-js/CHANGELOG.md
- CopilotKit/packages/sdk-js/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
- CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
- CopilotKit/utilities/eslint-config-custom/package.json
- CopilotKit/utilities/tailwind-config/CHANGELOG.md
- CopilotKit/utilities/tailwind-config/package.json
- CopilotKit/utilities/tsconfig/CHANGELOG.md
- CopilotKit/utilities/tsconfig/package.json
> Pre release pre/1.4.3

- docs/content/docs/coagents/quickstart.mdx
- docs/snippets/langgraph-platform-deployment-tabs.mdx
> docs: self hosted LG.js / LG platform

- CopilotKit/.changeset/config.json
- CopilotKit/.changeset/few-spoons-pay.md
- CopilotKit/examples/next-openai/README.md
- CopilotKit/packages/react-core/README.md
- CopilotKit/pnpm-lock.yaml
- examples/Dockerfile.ui
> test changeset bot

- examples/coagents-ai-researcher/ui/package.json
- examples/coagents-ai-researcher/ui/pnpm-lock.yaml
- examples/coagents-ai-researcher/ui/tsconfig.json
- examples/coagents-qa-native/ui/package.json
- examples/coagents-qa-native/ui/pnpm-lock.yaml
- examples/coagents-qa-text/ui/package.json
- examples/coagents-qa-text/ui/pnpm-lock.yaml
- examples/coagents-qa/ui/package.json
- examples/coagents-qa/ui/pnpm-lock.yaml
- examples/coagents-research-canvas/ui/package.json
- examples/coagents-research-canvas/ui/pnpm-lock.yaml
- examples/coagents-research-canvas/ui/tsconfig.json
- examples/coagents-routing/ui/package.json
- examples/coagents-routing/ui/pnpm-lock.yaml
- examples/coagents-shared-state/ui/package.json
- examples/coagents-shared-state/ui/pnpm-lock.yaml
- examples/coagents-starter/ui/package.json
- examples/coagents-starter/ui/pnpm-lock.yaml
- examples/coagents-travel/ui/package.json
- examples/coagents-travel/ui/pnpm-lock.yaml
- examples/coagents-wait-user-input/ui/package.json
- examples/coagents-wait-user-input/ui/pnpm-lock.yaml
Bump the UIs of example apps to React 19 and Next 15.
> feat(examples): bump to Next 15 and React 19

- .github/workflows/release.yml
- CopilotKit/.changeset/odd-moons-wash.md
- CopilotKit/packages/runtime/README.md
Testing the `next` prerelease.
> feat(runtime): readme update

- CopilotKit/.changeset/eighty-peaches-beam.md
- CopilotKit/packages/runtime/README.md
> fix(runtime): remove comment from readme

- examples/e2e/reporters/structured-reporter.ts
> remove flaky reporting

- CopilotKit/packages/react-ui/src/components/help-modal/icons.tsx
- CopilotKit/packages/react-ui/src/components/help-modal/modal.tsx
Adding the contact form that was previously commented out
> fix: add contact form for help from cpk team

- docs/content/docs/coagents/tutorials/ai-travel-app/index.mdx
- docs/content/docs/coagents/tutorials/ai-travel-app/meta.json
Replacing the iframe with a video and fixing an issue where the index of the tutorial was incorrect
> docs(coagents): add gif to travel tutorial and fix index page

- examples/Dockerfile.agent
- examples/coagents-ai-researcher/agent/poetry.lock
- examples/coagents-ai-researcher/agent/pyproject.toml
- examples/coagents-qa-native/agent/poetry.lock
- examples/coagents-qa-native/agent/pyproject.toml
- examples/coagents-qa-text/agent/poetry.lock
- examples/coagents-qa-text/agent/pyproject.toml
- examples/coagents-qa/agent/poetry.lock
- examples/coagents-qa/agent/pyproject.toml
- examples/coagents-research-canvas/agent/poetry.lock
- examples/coagents-research-canvas/agent/pyproject.toml
- examples/coagents-routing/agent/poetry.lock
- examples/coagents-routing/agent/pyproject.toml
- examples/coagents-shared-state/agent/poetry.lock
- examples/coagents-shared-state/agent/pyproject.toml
- examples/coagents-starter/agent/poetry.lock
- examples/coagents-starter/agent/pyproject.toml
- examples/coagents-travel/agent/poetry.lock
- examples/coagents-travel/agent/pyproject.toml
- examples/coagents-wait-user-input/agent/poetry.lock
- examples/coagents-wait-user-input/agent/pyproject.toml
> fixes python dependency in docker

- examples/coagents-research-canvas/agent/pyproject.toml
- examples/coagents-routing/agent/pyproject.toml
- examples/coagents-shared-state/agent/pyproject.toml
- examples/coagents-starter/agent/pyproject.toml
- examples/coagents-wait-user-input/agent/pyproject.toml
> removes ununsed deps array from project

- CopilotKit/packages/react-core/src/hooks/use-coagent-state-render.ts
- README.md
- docs/content/docs/coagents/chat-ui/hitl.mdx
- docs/content/docs/coagents/chat-ui/render-agent-state.mdx
- docs/content/docs/coagents/react-ui/hitl.mdx
- docs/content/docs/reference/hooks/useCoAgentStateRender.mdx
- Fixing reference to useCoagentStateRender to be useCoAgentStateRender
- Addressing some typos in the HITL docs and adding some accordions
- Updating the agentic generative UI guide to be clearer and easier to follow
> Tweaks for HITL docs and Agentic Generative UI

- .github/workflows/cleanup-caches-after-pr-close.yml
- .github/workflows/cleanup-caches-by-a branch.yml
[Clean up doc](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries)
> chore: clean up caches after PR is merged

- CopilotKit/packages/runtime/src/lib/logger.ts
These didn't help fix the underlying problem in cloudflare so no point keeping them
These didn't help fix the underlying problem in cloudflare so no point keeping them
> reverts redact changes

- docs/content/docs/coagents/chat-ui/hitl.mdx
- docs/content/docs/coagents/react-ui/hitl.mdx
- docs/content/docs/coagents/troubleshooting/common-issues.mdx
The guides for HITL now have options where the user can opt-in to do text based instead of JSON based human in the loop.
> docs(coagents): add text based human-in-the-loop accordions

- examples/coagents-research-canvas/agent/research_canvas/agent.py
- examples/coagents-research-canvas/agent/research_canvas/chat.py
convert research agent to LangGraph Command based routing
> convert research agent to LangGraph Command based routing

- CopilotKit/examples/next-openai/src/app/page.tsx
- CopilotKit/packages/react-ui/src/components/help-modal/modal.tsx
Several changes required for the help button.
We will now link to the faq section in the docs, and also make it more clear that this is a help button
> fix: change button and add docs faq link

- docs/components/layout/top-bar.tsx
- docs/components/react/link-to-copilot-cloud.tsx
Adds a little CTA in the top-right that will know if you've logged into Copilot Cloud or not and change accordingly.
> docs: add copilot cloud CTA

- CopilotKit/.changeset/young-knives-hide.md
- CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
This change allows user to configure non-agent CopilotKit Remote Endpoint.  
> fix: allow CopilotKit Remote Endpoint without agents

- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
- CopilotKit/packages/react-core/src/components/error-boundary/error-boundary.tsx
- CopilotKit/packages/react-core/src/components/error-boundary/error-utils.tsx
- CopilotKit/packages/react-core/src/components/toast/toast-provider.tsx
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-coagent.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-action.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-runtime-client.ts
- CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
- CopilotKit/packages/runtime/src/service-adapters/events.ts
- CopilotKit/packages/shared/src/types/index.ts
- CopilotKit/packages/shared/src/types/utility.ts
This PR introduces the usage of toasts (which we already had) in order to handle errors better and surface them to the developers.
> Error handling improvements

- docs/content/docs/(root)/guides/backend-actions/remote-backend-endpoint.mdx
- docs/content/docs/coagents/quickstart.mdx
- examples/coagents-ai-researcher/agent/ai_researcher/demo.py
- examples/coagents-qa-native/agent/email_agent/demo.py
- examples/coagents-qa-text/agent/greeting_agent/demo.py
- examples/coagents-qa/agent/my_agent/demo.py
- examples/coagents-research-canvas/agent/research_canvas/demo.py
- examples/coagents-routing/agent/my_agent/demo.py
- examples/coagents-shared-state/agent/my_agent/demo.py
- examples/coagents-starter/agent/my_agent/demo.py
- examples/coagents-travel/agent/travel/demo.py
- examples/coagents-wait-user-input/agent/my_agent/demo.py
- sdk-python/copilotkit/__init__.py
- sdk-python/copilotkit/demos/ai_researcher/demo.py
- sdk-python/copilotkit/demos/autotale_ai/demo.py
- sdk-python/copilotkit/demos/multi_agent/demo.py
- sdk-python/copilotkit/demos/multi_agent_anthropic/demo.py
- sdk-python/copilotkit/demos/qa/demo.py
- sdk-python/copilotkit/demos/research_canvas/demo.py
- sdk-python/copilotkit/demos/starter/demo.py
- sdk-python/copilotkit/demos/wait_user_input/demo.py
- sdk-python/copilotkit/integrations/fastapi.py
- sdk-python/copilotkit/sdk.py
Renaming some classes on our python SDK. All fully backwards compatible
> fix: rename py sdk class

- docs/content/docs/(root)/guides/custom-ai-assistant-behavior.mdx
Updating this page to be formatted a bit more intuitively and also add some a link to our system prompt so users can read it before deciding to change it.
> docs: update customize AI assistant behavior page

- .github/workflows/custom-prerelease.yml
- CopilotKit/.changeset/neat-stingrays-appear.md
- CopilotKit/scripts/release/prepare-custom-prerelease.sh
- README.md
> test: custom tag prerelease

- docs/content/docs/(root)/guides/connect-your-data.mdx
- Remove non-existent useColleagues custom hook
- Add useState with sample colleague data for clearer documentation
- Keep core useCopilotReadable functionality unchanged
> refactor: replace useColleagues with useState hook in docs example

- sdk-python/copilotkit/state.py
…rsions
import TypedDict from typing_extensions to be compatible with earlier python versions
> import TypedDict from typing_extensions

- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
- docs/content/docs/reference/hooks/useCopilotChat.mdx
add followUp option to appendMessage
> add followUp option to appendMessage

- docs/content/docs/(root)/guides/generative-ui.mdx
Adding an overview to the page, reformatting and adding an explanation of statuses.
> docs(generative-ui): reformat and add explanation about render statuses

- docs/content/docs/(root)/quickstart.mdx
- docs/content/docs/coagents/quickstart.mdx
> add turbopack callout

- docs/app/layout.tsx
- docs/content/docs/(root)/guides/copilot-textarea.mdx
- docs/content/docs/(root)/quickstart.mdx
- docs/content/docs/(root)/tutorials/ai-powered-textarea/step-2-setup-copilotkit.mdx
- docs/content/docs/(root)/tutorials/ai-todo-app/step-2-setup-copilotkit.mdx
- docs/content/docs/coagents/index.mdx
- docs/snippets/install-sdk.mdx
Reverts CopilotKit/CopilotKit#1233
> Revert "fix install versions"

- docs/content/docs/(root)/guides/copilot-textarea.mdx
- docs/content/docs/(root)/quickstart.mdx
- docs/content/docs/(root)/tutorials/ai-powered-textarea/step-2-setup-copilotkit.mdx
- docs/content/docs/(root)/tutorials/ai-todo-app/step-2-setup-copilotkit.mdx
- docs/content/docs/coagents/index.mdx
- docs/snippets/install-sdk.mdx
Removing pinned version in docs install script
> fix(docs): installation version

- docs/content/docs/coagents/tutorials/ai-travel-app/step-4-integrate-the-agent.mdx
- docs/content/docs/coagents/tutorials/ai-travel-app/step-5-stream-progress.mdx
- docs/content/docs/coagents/tutorials/ai-travel-app/step-6-human-in-the-loop.mdx
Adding back in some content that was changed or removed. Without these changes the tutorial will not work properly.
Additionally, adding in some new or updated content to improve the UX of the tutorial.
> fix(docs): revert changes to travel tutorial that break it

- CopilotKit/.changeset/warm-cats-swim.md
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-copilot-chat.ts
This PR tweaks the behavior of code & llm when an error happens when actions are called and fails
> fix: handle copilot action errors

- examples/coagents-research-canvas/ui/src/app/Main.tsx
put useCopilotChatSuggestions back
> put useCopilotChatSuggestions back

- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
> Silence LG platform error

- docs/app/(home)/layout.tsx
- docs/content/docs/(root)/guides/backend-actions/remote-backend-endpoint.mdx
- docs/content/docs/(root)/index.mdx
- docs/content/docs/coagents/index.mdx
- docs/snippets/install-python-sdk.mdx
> docs: lots of polish and refinement of messages

- examples/coagents-qa-native/agent-js/package.json
- examples/coagents-qa-native/agent-js/pnpm-lock.yaml
- examples/coagents-qa-text/agent-js/package.json
- examples/coagents-qa-text/agent-js/pnpm-lock.yaml
- examples/coagents-research-canvas/agent-js/package.json
- examples/coagents-research-canvas/agent-js/pnpm-lock.yaml
- examples/coagents-routing/agent-js/package.json
- examples/coagents-routing/agent-js/pnpm-lock.yaml
> fix(examples): no version pinning for sdk js

- docs/app/(home)/[[...slug]]/page.tsx
- docs/content/docs/(root)/guides/authenticated-actions.mdx
- docs/content/docs/(root)/guides/guardrails.mdx
- docs/content/docs/(root)/guides/meta.json
> docs: adds cloud only feature

- docs/snippets/self-hosting-copilot-runtime-create-endpoint.mdx
- Wrap handler in async IIFE to properly handle Promises
- Remove incompatible next() parameter from handler call 
- Add error handling via .catch(next)
Fixes TypeScript error from type mismatch between Express and GraphQL Yoga request objects
> fix(docs): correct Express.js runtime handler implementation

- examples/Dockerfile.agent-js
- examples/Dockerfile.ui
Temporary fix here:
https://github.com/pnpm/pnpm/issues/9029
> fix(monorepo): corepack build issue

- .github/workflows/destroy-inactive-preview-environments.yml
- examples/helmfile/.gitignore
- examples/helmfile/destroy-inactive-preview-environments.js
> Destroy hanging preview environments after 12 hours of inactivity

- examples/coagents-qa-text/agent/greeting_agent/demo.py
- sdk-python/copilotkit/integrations/fastapi.py
Enable running fastapi endpoint without thread pool
> fix: fastapi no thread pool

- CopilotKit/examples/state-machine/src/app/globals.css
- CopilotKit/examples/state-machine/src/app/layout.tsx
- CopilotKit/examples/state-machine/src/components/car-sales-chat.tsx
- CopilotKit/examples/state-machine/src/components/chat-message.tsx
- CopilotKit/examples/state-machine/src/components/order-cards.tsx
- CopilotKit/examples/state-machine/src/components/state-visualizer.tsx
- CopilotKit/examples/state-machine/src/components/tabs.tsx
This PR applies a new design for the state machine demo by @tylerslaton
> chore: state machine redesign

- CopilotKit/.changeset/serious-penguins-sniff.md
- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
- Actions were being incorrectly filtered in multi-agent scenarios
- All LangGraph agent actions were being filtered out, preventing agent-to-agent communication
1. Improved action filtering logic to:
- Keep all regular (non-agent) actions
- Keep other agents' actions while preventing self-calls
2. Enhanced code readability with clearer variable names:
- agent -> currentAgent
- serverSideActionsInput -> availableActionsForCurrentAgent
- actionInputsWithoutAgents -> allAvailableActions
3. Added explicit comments documenting the filtering logic
1. Basic Multi-Agent Flow:
```typescript
const vacationAgent = "vacation-agent"
const bookingAgent = "booking-agent"
// Verify vacation-agent can call booking-agent
// Expected: booking-agent's actions appear in availableActionsForCurrentAgent
```
2. …
> fix(runtime): enable multi-agent flows while preventing recursive self-calls

- CopilotKit/packages/react-ui/src/components/dev-console/console.tsx
> update install step

- CopilotKit/.changeset/pre.json
> release 1.5.15

- examples/coagents-qa-native/agent-js/package.json
- examples/coagents-qa-native/agent-js/pnpm-lock.yaml
fix coagents qa native deployment but specifying package manager
> chore: fix coagents qa native deployment but specifying package manager

- examples/coagents-qa-native/agent-js/package.json
- examples/coagents-qa-native/agent-js/pnpm-lock.yaml
Reverts CopilotKit/CopilotKit#1335
did not fix
> Revert "chore: fix coagents qa native deployment but specifying package manager"

- sdk-python/pyproject.toml
Releasing python sdk version 0.1.36
> release python version 0.1.36

- CopilotKit/.changeset/polite-eyes-check.md
- CopilotKit/packages/runtime-client-gql/src/client/CopilotRuntimeClient.ts
- CopilotKit/packages/runtime/src/lib/integrations/shared.ts
- CopilotKit/packages/runtime/tsconfig.json
- CopilotKit/packages/shared/src/utils/errors.ts
- package.json
Misaligned versions could cause unexpected errors. In this PR, the misalignment can be detected and alerted
> fix: detect and alert on version mismatch

- CopilotKit/.changeset/pre.json
> release-1.5.16

- examples/coagents-starter/README.md
> Update the CoAgents Starter README.md to include the JS-SDK

- docs/content/docs/coagents/advanced/emit-messages.mdx
- docs/content/docs/coagents/human-in-the-loop/interrupt-flow.mdx
There was a typo in the python variant of this example that will now be fixed.
> fix(docs): address typo in emit message guide

- CopilotKit/packages/runtime/src/graphql/resolvers/state.resolver.ts
- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
- CopilotKit/scripts/develop/example.sh
- examples/coagents-research-canvas/agent/research_canvas/demo.py
- sdk-python/copilotkit/agent.py
- sdk-python/copilotkit/integrations/fastapi.py
- sdk-python/copilotkit/langgraph_agent.py
> Fix concurrency issues

- CopilotKit/.changeset/tricky-walls-promise.md
- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
- CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
- CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts
- CopilotKit/packages/shared/src/utils/errors.ts
This PR adds some more information to our already existing error messages. This should make it easier to debug where the error originates from
> fix: add additional info the our error messages

- CopilotKit/.changeset/lemon-worms-refuse.md
- CopilotKit/packages/sdk-js/package.json
- CopilotKit/pnpm-lock.yaml
Fixes https://github.com/CopilotKit/CopilotKit/issues/1296
> fix: add types for js sdk export

- docs/content/docs/coagents/human-in-the-loop/node-flow.mdx
Adding in a typescript guide for node hitl
> docs(node-hitl): add typescript guide

- CopilotKit/.changeset/pre.json
> exit pre mode

- sdk-python/pyproject.toml
> bump python

- docs/content/docs/coagents/quickstart/langgraph.mdx
- docs/snippets/langgraph-platform-deployment-tabs.mdx
Previously, the quickstart was a bit hard to follow for the JS variant of the `coagent-starter`. This addresses that.
> docs(coagents): add clearer instructions for js coagents starter

- CopilotKit/.changeset/few-scissors-greet.md
- CopilotKit/packages/shared/src/utils/errors.ts
Fixing wrong arguments for error resolver, causing an error from inside the error
> fix(errors): fix internal usage of error resolver

- docs/content/docs/(root)/troubleshooting/common-issues.mdx
- docs/content/docs/coagents/troubleshooting/common-issues.mdx
Adds a new troubleshooting section to help users diagnose tunnel connection issues. The section includes:
- Common symptoms (indefinite spinning during tunnel creation)
- Specific commands to verify connectivity
- Potential solutions if connection is blocked by router/ISP
N/A
> docs: add troubleshooting guide for tunnel connection issues

- CopilotKit/.changeset/pre.json
> release 1.5.20

- docs/snippets/self-hosting-copilot-runtime-create-endpoint.mdx
> docs: add serverless timeout warning and solutions

- CopilotKit/.changeset/healthy-foxes-serve.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/pnpm-lock.yaml
This is a missing dependency which can affect running local runtime CPK
> fix: add class validator to dependencies

- docs/snippets/langgraph-platform-deployment-tabs.mdx
- docs/snippets/self-hosting-copilot-runtime-starter.mdx
- docs/snippets/self-hosting-remote-endpoints.mdx
- examples/coagents-starter/agent-py/sample_agent/demo.py
> fix(docs): address docs stress-test issues

- docs/content/docs/coagents/quickstart/langgraph.mdx
Adding a bandaid fix to a missing dependency while we fix.
> fix(docs): add class-validator to quickstart install

- docs/content/docs/coagents/advanced/disabling-state-streaming.mdx
- docs/content/docs/coagents/advanced/exit-agent.mdx
- docs/content/docs/coagents/human-in-the-loop/interrupt-flow.mdx
- docs/content/docs/coagents/shared-state/predictive-state-updates.mdx
> fix js docs

- CopilotKit/packages/react-core/src/hooks/use-chat.ts
- CopilotKit/packages/react-core/src/hooks/use-coagent.ts
- CopilotKit/packages/runtime-client-gql/src/client/conversion.ts
- CopilotKit/packages/runtime-client-gql/src/client/types.ts
- CopilotKit/packages/runtime/src/lib/runtime/remote-action-constructors.ts
- CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
- CopilotKit/packages/runtime/src/service-adapters/conversion.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/utils.ts
- CopilotKit/packages/shared/src/utils/index.ts
Adding a utility function that wraps JSON parsing and uses fallback when needed
> fix: handle unparsable json and provide fallback where needed

- examples/coagents-starter/README.md
Updating the messaging to be clearer for the coagents starter
> feat: update coagents-starter readme

- docs/content/docs/coagents/tutorials/agent-native-app/step-2-start-the-agent.mdx
> fix(ana-tutorial): adding pip install command to start the agent

- CopilotKit/.changeset/pre.json
> release 1.6.0

- examples/copilot-form-filling/components/IncidentReportForm.tsx
Fixing a small linter issue preventing deployment.
> fix(copilot-form-filling): fix small linting issue

- docs/content/docs/(root)/cookbook/state-machine.mdx
- docs/content/docs/(root)/guides/connect-your-data/backend.mdx
- docs/content/docs/(root)/guides/connect-your-data/frontend.mdx
- docs/content/docs/(root)/guides/connect-your-data/index.mdx
- docs/content/docs/(root)/guides/connect-your-data/meta.json
- docs/content/docs/(root)/guides/custom-ai-assistant-behavior.mdx
- docs/content/docs/(root)/guides/frontend-actions.mdx
Splitting the "connect your data" doc into two separate pages.
> docs: split connect your data into frontend and backend

- examples/copilot-chat-with-your-data/README.md
Now that this is hosted in vercel, adding a link to it.
> chore: add hosted link for chat with your data example

- examples/copilot-state-machine/package.json
- examples/copilot-state-machine/pnpm-lock.yaml
Needed to add a package so that Vercel can build properly
> fix(state-machine): address linter issues blocking deployment

- docs/content/docs/coagents/tutorials/agent-native-app/step-6-shared-state.mdx
- Fixing a typo in the file name for the ana tutorial.
> fix(ana-tutorial): fix typo in step 6

- docs/content/docs/coagents/human-in-the-loop/interrupt-flow.mdx
Just a small interrupt syntax error that needs fixing
> docs: fix issue with interrupt python syntax

- docs/content/docs/coagents/multi-agent-flows.mdx
- docs/content/docs/coagents/shared-state/predictive-state-updates.mdx
- docs/content/docs/crewai-crews/multi-agent-flows.mdx
- docs/content/docs/crewai-flows/multi-agent-flows.mdx
- docs/content/docs/crewai-flows/shared-state/predictive-state-updates.mdx
Small doc fixes and improvements
> docs: fix docs py syntax

- community/demos_2025/finance_ai.md
I updated the `demos_2025` folder with information about the AI-powered open-source Financial Manager built using Maybe Finance + CopilotKit🪁
> updated info about finance_ai

- sdk-python/copilotkit/crewai/crewai_sdk.py
- sdk-python/copilotkit/runloop.py
Fix CrewAI pydantic state issues
> Fix CrewAI pydantic state issues

- examples/demo-viewer/package.json
- examples/demo-viewer/pnpm-lock.yaml
- examples/demo-viewer/src/app/api/fs/route.ts
- examples/demo-viewer/src/app/page.tsx
- examples/demo-viewer/src/components/code-editor/code-editor.tsx
- examples/demo-viewer/tailwind.config.ts
Several build issues when building with vercel
> chore: fix build issues for demo viewer

- examples/demo-viewer/src/app/api/copilotkit/route.ts
enable using agent from remote endpoint
> chore: enable using agent from remote endpoint

- docs/content/docs/crewai-crews/quickstart/crewai.mdx
> update link to the demo

- examples/coagents-research-canvas/ui/src/app/api/copilotkit/route.ts
- examples/coagents-research-canvas/ui/src/app/page.tsx
- Fix bug in agent routing - properly handle model switching and API endpoints
- N/A
> add multi-agent support with model selector

- CopilotKit/.changeset/funny-needles-reflect.md
- CopilotKit/packages/react-ui/src/components/crew/DefaultResponseRenderer.tsx
- CopilotKit/packages/react-ui/src/components/crew/DefaultStateRenderer.tsx
- CopilotKit/packages/react-ui/src/components/crew/index.ts
- CopilotKit/packages/react-ui/src/components/crew/types.ts
- CopilotKit/packages/react-ui/src/components/index.ts
- CopilotKit/packages/react-ui/src/css/crew.css
- CopilotKit/packages/react-ui/src/styles.css
Add new generic, customizable UI components:
- Create DefaultResponseRenderer for approval/rejection flows
- Create DefaultStateRenderer for visualizing agent state and progress
- Define comprehensive TypeScript interface definitions in types.ts
- Implement CSS styling with light/dark mode support in crew.css
- Build components as framework-agnostic with no external dependencies
- Provide extensive customization options via props
- Include detailed documentation and examples
> chore(react-ui): Add DefaultResponseRenderer and DefaultStateRenderers

- docs/content/docs/crewai-crews/components/index.mdx
- docs/content/docs/crewai-crews/components/response-renderer.mdx
- docs/content/docs/crewai-crews/components/state-renderer.mdx
- docs/content/docs/crewai-crews/components/types.mdx
- docs/content/docs/crewai-crews/concepts/crewai.mdx
- docs/content/docs/crewai-crews/generative-ui/index.mdx
- docs/content/docs/crewai-crews/meta.json
- docs/content/docs/crewai-crews/quickstart/crewai.mdx
- docs/lib/icons/custom-icons.tsx
Add comprehensive documentation for CopilotKit UI components used with CrewAI:
- Create dedicated components section with index page
- Add state-renderer documentation with examples and API reference
- Add response-renderer documentation with examples and API reference
- Add TypeScript interfaces and types documentation
- Update related docs to reference the new components section
- Add components entry to site navigation
> docs: add CrewAI UI components documentation

- docs/content/docs/(root)/guides/frontend-actions.mdx
Fixing a small typo in the docs and clarifying how the available prop works.
> fix: address issue with action documentation

- docs/content/docs/coagents/human-in-the-loop/interrupt-flow.mdx
Delivering docs for `copilotkit_interrupt` fn
> docs: add documentation for copilotkit interrupt

- CopilotKit/.changeset/silver-moose-sleep.md
- CopilotKit/examples/next-openai/src/app/presentation/page.tsx
- CopilotKit/examples/next-openai/src/styles/globals.css
- CopilotKit/packages/react-ui/src/components/chat/Input.tsx
- CopilotKit/packages/react-ui/src/css/button.css
- CopilotKit/packages/react-ui/src/css/colors.css
- CopilotKit/packages/react-ui/src/css/console.css
- CopilotKit/packages/react-ui/src/css/header.css
- CopilotKit/packages/react-ui/src/css/input.css
- CopilotKit/packages/react-ui/src/css/messages.css
- CopilotKit/packages/react-ui/src/css/suggestions.css
- docs/components/react/copilotkit-css.tsx
- docs/content/docs/(root)/guides/custom-look-and-feel/customize-built-in-ui-components.mdx
- examples/coagents-research-canvas/ui/src/app/Main.tsx
- examples/coagents-research-canvas/ui/src/app/globals.css
In preparation to the next release, some fixes for API compatibility of the new redesign
> fix: re-align customization variable names and usage

- CODE_OF_CONDUCT.md
Fix the link in the CODE_OF_CONDUCT.
> docs: fix contribution link in code_of_conduct.md

- CopilotKit/packages/react-ui/src/css/colors.css
- CopilotKit/packages/react-ui/src/css/panel.css
- docs/app/layout.tsx
- docs/components/layout/banners.tsx
- docs/components/react/component-previews/new-look-and-feel.tsx
- docs/content/docs/(root)/troubleshooting/meta.json
- docs/content/docs/(root)/troubleshooting/migrate-to-1.8.0.mdx
- docs/package.json
- docs/pnpm-lock.yaml
Fixing some styles and adding a new migration document for upcoming 1.8.0 release
> docs: add migration document for 1.8.0

- registry/components/runtime/remote-endpoint.ts
Builds were failing due to linter issues.
> fix: address linter issues with registry

- docs/content/docs/crewai-crews/quickstart/crewai.mdx
- docs/snippets/crew-quickstart.mdx
> updates to use hook

- CopilotKit/.changeset/nasty-tigers-draw.md
- CopilotKit/packages/react-core/src/components/copilot-provider/copilotkit.tsx
Copy of https://github.com/CopilotKit/CopilotKit/pull/1501
> fix(react-core): update agentSession when agent props change #1497

- registry/components/quickstarts/coagents-starter.tsx
- registry/public/r/agent-starter.json
- registry/public/r/coagents-starter-ui.json
- registry/registry.json
Adding a new entry for the coagent's starter
> feat: add new registry entry for coagents starter UI

- registry/public/r/langgraph-platform-runtime.json
- registry/public/r/remote-endpoint.json
- registry/public/r/standard-runtime.json
- registry/registry.json
Adding runtimes to our component registry.
> feat: add runtimes to our registry

- sdk-python/copilotkit/langgraph_agent.py
Improve fetching of input and output schemas
> fix: improve schema fetching for langgraph agent

- examples/coagents-ai-researcher/wfcms-data.json
- examples/coagents-research-canvas/wfcms-data.json
- examples/coagents-travel/wfcms-data.json
- examples/copilot-chat-with-your-data/wfcms-data.json
- examples/copilot-form-filling/wfcms-data.json
- examples/copilot-state-machine/wfcms-data.json
Adding data files to automatically sync examples into our marketing site.
> feat: add wfcms-data.json files for demos in marketing site

- CopilotKit/.changeset/mean-crabs-enjoy.md
- CopilotKit/.changeset/pre.json
- CopilotKit/.changeset/red-plums-notice.md
- CopilotKit/.changeset/tiny-comics-study.md
- CopilotKit/.changeset/twenty-houses-end.md
- CopilotKit/changelog.txt
> release v1.8.2

- sdk-python/README.md
- Add badges for PyPI version and license
- Include clear feature list and installation instructions
- Add quick start code example
- Include documentation and support links
- Follow PyPI best practices for package documentation
> docs(python): add comprehensive PyPI-ready README

- registry/registry.json
Needed to have the react ui dep here
> fix: add react-ui to coagents-crew-starter

- docs/app/global.css
- docs/components/layout/banners.tsx
Adding a crew-ai announcement banner
> docs: crew-ai announcement banner

- registry/public/r/coagents-crew-starter.json
Registry wasn't built when it needed to be
> fix: build registry

- docs/components/layout/banners.tsx
> fix: address issue preventing banner from closing on docs

- docs/content/docs/coagents/shared-state/state-inputs-outputs.mdx
Document support of input/output schemas for typescript
> docs: document support for inputs and outputs schema for JS agents

- CopilotKit/.changeset/four-wombats-obey.md
- CopilotKit/packages/react-ui/src/components/chat/Header.tsx
- CopilotKit/packages/react-ui/src/components/dev-console/console.tsx
- CopilotKit/packages/react-ui/src/css/header.css
- CopilotKit/packages/react-ui/src/css/messages.css
Small fixes of styles. Mostly around disabling possible browser styles that may appear and temper with ours
> fix: fix default styles of chat components

- CopilotKit/packages/react-core/CHANGELOG.md
- CopilotKit/packages/react-core/package.json
- CopilotKit/packages/react-textarea/CHANGELOG.md
- CopilotKit/packages/react-textarea/package.json
- CopilotKit/packages/react-ui/CHANGELOG.md
- CopilotKit/packages/react-ui/package.json
- CopilotKit/packages/runtime-client-gql/CHANGELOG.md
- CopilotKit/packages/runtime-client-gql/package.json
- CopilotKit/packages/runtime/CHANGELOG.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/sdk-js/CHANGELOG.md
- CopilotKit/packages/sdk-js/package.json
- CopilotKit/packages/shared/CHANGELOG.md
- CopilotKit/packages/shared/package.json
> patch version in package.json manually

- docs/content/docs/(root)/troubleshooting/common-issues.mdx
fixed typo: python's instead of pytho's
> fixed typo: python's instead of pytho's

- docs/content/docs/coagents/persistence/message-persistence.mdx
> chore: add missing await in checkpoint setup command

- docs/content/docs/(root)/guides/authenticated-actions.mdx
> fixes `authConfig_c` doc

- CopilotKit/packages/react-ui/src/components/chat/Modal.tsx
- docs/content/docs/(root)/guides/custom-look-and-feel/customize-built-in-ui-components.mdx
- docs/content/docs/coagents/advanced/emit-messages.mdx
Bundling several tiny fixes together. View them commit by commit to know what changed
> fix: tiny fixes bundle

- CopilotKit/.changeset/witty-poets-do.md
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderActionExecutionMessage.tsx
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderAgentStateMessage.tsx
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderResultMessage.tsx
- CopilotKit/packages/react-ui/src/components/chat/messages/RenderTextMessage.tsx
- CopilotKit/packages/react-ui/src/components/chat/props.ts
As we provide default components, we should allow the dynamically not supply them
> fix: for every component that has default, make prop optional

- docs/content/docs/coagents/human-in-the-loop/interrupt-flow.mdx
This PR adds examples and documentation on the two different options we have for langgraph interrupt: the handler and the conditional.
> chore: document conditionals and handler for interrupt

- docs/content/docs/(root)/index.mdx
Overhauling the landing page to be visually better laid out with more concrete content.
> docs: overhaul landing page

- docs/app/global.css
- docs/components/layout/banners.tsx
Removing the banner for CrewAI event that's already happened
> docs: remove old event

- docs/content/docs/coagents/shared-state/predictive-state-updates.mdx
Tool based predictive state updates on python docs does not lead to working code. This is the fix
> chore: fix documentation for tool based predictive state updates

- CopilotKit/.changeset/gentle-ads-check.md
- CopilotKit/packages/react-ui/src/components/chat/Window.tsx
- CopilotKit/packages/react-ui/src/css/input.css
- CopilotKit/packages/react-ui/src/css/window.css
- CopilotKit/packages/react-ui/src/hooks/use-dark-mode.ts
Adding the "powered by copilotkit" to the chat
> feat: add powered-by-copilotkit watermark

- CopilotKit/packages/react-ui/src/css/window.css
- docs/components/react/copilotkit-css.tsx
> chore: explain removal of watermark in docs

- docs/content/docs/crewai-flows/advanced/exit-agent.mdx
- examples/coagents-starter-crewai-flows/agent-py/sample_agent/agent.py
- examples/coagents-starter-crewai-flows/agent-py/sample_agent/demo.py
> exit case fixes

- docs/public/llms.txt
Adding in a new `llms.txt` file!
> feat: add static llms.txt file

- sdk-python/pyproject.toml
> bump sdk-python version

- examples/demo-viewer/package.json
- examples/demo-viewer/pnpm-lock.yaml
> use 1.8.4 official release in demo viewer

- docs/content/docs/crewai-flows/generative-ui/agentic.mdx
- docs/content/docs/crewai-flows/persistence/loading-agent-state.mdx
- docs/content/docs/crewai-flows/persistence/loading-message-history.mdx
- docs/content/docs/crewai-flows/persistence/message-persistence.mdx
- docs/content/docs/crewai-flows/shared-state/predictive-state-updates.mdx
> fix: update doc on agentic generative ui

- docs/content/docs/(root)/guides/meta.json
- docs/content/docs/(root)/guides/model-context-protocol.mdx
> docs: add guide for integrating MCP servers with CopilotKit

- examples/demo-viewer/agent/demo/langgraph_agentic_chat/agent.py
- examples/demo-viewer/agent/demo/langgraph_agentic_generative_ui/agent.py
- examples/demo-viewer/agent/demo/langgraph_human_in_the_loop/agent.py
- examples/demo-viewer/agent/demo/langgraph_predictive_state_updates/agent.py
- examples/demo-viewer/agent/demo/langgraph_shared_state/agent.py
> added exiting agent loop in examples/demo-viewer

- examples/coagents-starter/agent-py/sample_agent/agent.py
> fix: removes memory saver

- CopilotKit/.changeset/pre.json
> release 1.8.7

- CopilotKit/.changeset/pre.json
1. **Renamed Property**: `mcpEndpoints` → `mcpServers`
- Applied consistently across the codebase
- Affects API signatures in multiple components and interfaces
2. **API Interface Changes**:
- Removed `mcpEndpoints` prop from `CopilotKitProps` interface 
- Changed `CopilotApiConfig` interface to use `mcpServers` instead of `mcpEndpoints`
- Added new interface `MCPServerConfig` with `endpoint` and optional `apiKey` properties
- Updated `useCopilotChat` return interface to expose `mcpServers` and `setMcpServers` methods
3. **Runtime Configuration**:
- Renamed property in `CopilotRuntimeConstructorParams` from `mcpEndpoints` to `mcpServers`
- Updated validation messages and internal variable names
- Added backward compatibility for `properties.mcpEndpoints` alongside `properties.mcpServers` …
> releases 1.8.8

- docs/content/docs/(root)/guides/model-context-protocol.mdx
> Improve MCP documentation with better structure and clearer instructions

- docs/content/docs/(root)/guides/model-context-protocol.mdx
Updating the MCP documentation to be clearer in structure and prominently feature composio.
> feat(docs): refactor MCP documentation page

- CopilotKit/.changeset/healthy-spoons-ring.md
- CopilotKit/packages/react-ui/src/components/chat/Input.tsx
- CopilotKit/packages/react-ui/src/css/input.css
Currently the input box takes only one line at a time. This PR allows an expanding box, up to 6 lines.
> fix: allow the chat input to expand on new lines

- docs/content/docs/(root)/guides/model-context-protocol.mdx
We had a typo in the imports here, pretty quick fix.
> fix(docs): address issue in MCP doc having incorrect import

- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/runtime/src/lib/runtime/remote-lg-action.ts
- CopilotKit/pnpm-lock.yaml
> feat: use latest lg sdk to support latest features

- docs/content/docs/(root)/index.mdx
> docs: Fix typo

- docs/content/docs/(root)/guides/meta.json
- docs/content/docs/(root)/guides/model-context-protocol.mdx
Updating the CLI command to reflect what the current CLI implementation is for MCP
> docs(mcp): update CLI command for MCP doc

- CopilotKit/.changeset/khaki-laws-juggle.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/packages/runtime/src/lib/runtime/agentwire-action.ts
- CopilotKit/packages/runtime/src/lib/runtime/copilot-runtime.ts
- CopilotKit/packages/runtime/src/lib/runtime/remote-actions.ts
- CopilotKit/pnpm-lock.yaml
> updates ag-ui deps

- docs/content/docs/(root)/quickstart.mdx
Adding the CLI into the standard quickstart
> docs(quickstart): add cli command to standard quickstart

- docs/app/global.css
- docs/components/layout/banners.tsx
Adding launch banner for MCP support.
> feat(docs): add banner for mcp launch

- examples/demo-viewer/agent/demo/langgraph_human_in_the_loop/agent.py
> updated prompt of hitl

- examples/demo-viewer/agent/demo/crewai_tool_based_generative_ui/page.tsx
- examples/demo-viewer/agent/demo/langgraph_tool_based_generative_ui/page.tsx
> removed horizontal scroll for item lists

- CopilotKit/.changeset/polite-rabbits-unite.md
- CopilotKit/packages/react-ui/src/components/chat/Input.tsx
- CopilotKit/packages/react-ui/src/components/chat/Messages.tsx
Fixing an issue where CopilotKit would always scroll into view across the dom instead of just its container.
> fix(react-ui): fix scrolling into view issue

- sdk-python/copilotkit/langgraph_agent.py
Fixes https://github.com/CopilotKit/CopilotKit/issues/1739
> fix: refrain from overriding graph level config in python sdk

- sdk-python/pyproject.toml
Release python sdk version 0.1.45
> chore: release python sdk version 0.1.45

- CopilotKit/.changeset/pre.json
> chore: release 1.8.11

- examples/demo-viewer/agent/demo/langgraph_server.py
> Langgraph HITL issue fix

- CopilotKit/.changeset/itchy-apes-compete.md
- CopilotKit/packages/runtime/src/service-adapters/anthropic/anthropic-adapter.ts
- docs/components/react/multi-provider-content/utils.ts
Several fixes to docs and llm adapters
> fix: docs and quickstart fixes

- CopilotKit/.changeset/curly-peas-confess.md
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
- CopilotKit/packages/runtime/src/service-adapters/openai/openai-assistant-adapter.ts
- docs/content/docs/reference/classes/llm-adapters/OpenAIAdapter.mdx
- docs/content/docs/reference/classes/llm-adapters/OpenAIAssistantAdapter.mdx
resolves https://github.com/CopilotKit/CopilotKit/issues/1779
> feat: allow keeping system role for openai adapters

- CopilotKit/.changeset/orange-drinks-do.md
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
> fixes human in the loop flow 

- docs/content/docs/(root)/index.mdx
- docs/content/docs/ag2/index.mdx
- docs/content/docs/ag2/meta.json
Adding a card to the landing page for AG2 and embedding a starter example on the AG2 landing page.
> docs(landing): add AG2 card

- sdk-python/pyproject.toml
- Bumps CrewAI from 0.102.0 to 0.118.0
- https://github.com/CopilotKit/CopilotKit/issues/1667
> bumps python sdk to 0.1.46

- CopilotKit/.changeset/chatty-planes-join.md
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
> fix: stop passing config if not exists

- CopilotKit/.changeset/pre.json
* **Keep system role for OpenAI adapters** – Gives developers more control over agent identity in conversation flows.
* **New AG2 & Mastra demos** – Introduced feature viewers and starter templates for both AG2 and Mastra-powered agents.
* **MongoDB + Pinecone examples** – Added vector search demo integrations for fast prototyping.
* **Updated CoAgent Starter UI** – Visual refresh to better showcase CoAgent capabilities.
* **HITL (Human-in-the-loop)**: Fixed critical issues in approval and control handoff flows.
* **Chat UI**: Adjusted padding, input layout, and improved full-height display handling.
* **Tool result deduplication**: Now using allowlist-based prevention of duplicate tool responses.
* **Landing page & docs**: Added AG2 card, Mastra docs, and fixed tunneling-related Windows …
> release 1.8.12

- docs/components/layout/banners.tsx
- docs/components/layout/top-bar.tsx
- docs/components/react/link-to-copilot-cloud.tsx
- Adding a sign-in button
- Updating the banner
> feat(docs): change banner and add cloud sign-in button

- CopilotKit/.changeset/afraid-bottles-dress.md
- CopilotKit/packages/react-core/src/hooks/use-chat.ts
> fix followUp check

- CopilotKit/.changeset/pre.json
* **Feature Viewer (no chat mode)** introduced — improves the viewer UX without default chat panel (#1819, #1824)
* **Custom Markdown in Assistant Messages** now supported (#1726)
* **Suggestion List Replacement** added — users can now dynamically update suggestion lists (#1846)
* Updated `@copilotkit/sdk` to latest in **Demo Viewer** (#1821)
* **CrewAI HITL docs** updated to reflect new flow (#1837)
* Added **CrewAI Overview Page** and multiple flow/agent doc refinements (#1830–1835, #1831–#1834)
* Improved **styling, messaging, and clarity** across several docs pages (#1835)
* Banner and **Cloud Sign-In button** added to landing pages (#1844)
* Docs now include updated **Mastra tool-based usage** (#fix)
* `followUp` check logic fixed (#1849)
* Import cleanup and version bumps …
> release 1.8.13

- docs/content/docs/coagents/generative-ui/agentic.mdx
Fixing a small issue with the docs leading to broken code.
> docs: add await to ChatOpenAI call

- CopilotKit/.changeset/rich-drinks-arrive.md
- CopilotKit/packages/runtime/src/lib/runtime/agui-action.ts
Fixes missing piece in https://github.com/CopilotKit/CopilotKit/pull/1914
> fix: fix cpk agui wiring for langgraph

- CopilotKit/.changeset/pre.json
All notable changes to this project are documented here. We follow the **Keep a Changelog** convention.
* **CrewAI integration utilities** for CopilotKit enterprise workflows (#1941)
* **Cisco demo agent** & *Viewer‑No‑Chat* example (#1866, #1825)
* `jsonSchemaToActionParameters` helper + `getAllElements` debug API
* **mastra** CLI install instructions + new *rabbit* YAML demo
* Filter empty `AIMessages` in `GoogleGenerativeAIAdapter`
* Append follow‑up when `actions.disableFollowUp` is set (#1853)
* LangGraph wiring & config‑spread issues (#1916, #1904)
* Poetry install source URL + starter lockfiles (#1888, #1890)
* CopilotTextarea bugs & useless div cleanup (#kachurun)
* Runtime header injection in `useCoAgent` (#utvara)
* Merge‑state deprecation check inversion (#1749)
* Example …
> release 1.8.14

- sdk-python/pyproject.toml
Release python sdk version 0.1.51
> chore: release python sdk 0.1.51

- CopilotKit/packages/runtime/package.json
- CopilotKit/pnpm-lock.yaml
Reverts CopilotKit/CopilotKit#2145
Again, no changeset, need to revert.
> Revert "fix: use latest agui dependencies to include required fixes"

- CopilotKit/.changeset/sixty-rice-fail.md
- CopilotKit/packages/runtime/package.json
- CopilotKit/pnpm-lock.yaml
Merging https://github.com/CopilotKit/CopilotKit/pull/2145 again. This time with changeset
> fix: use latest agui dependencies to include required fixes

- docs/content/docs/langgraph/index.mdx
Change the link of LangGraph Quickstart
> fix - Change the link of LangGraph Quickstart

- docs/content/docs/langgraph/human-in-the-loop/interrupt-flow.mdx
Small doc fix: a comma was playing hide and seek!
n/a
> docs: fix a sneaky missing comma

- examples/ag2/starter/pnpm-lock.yaml
- examples/coagents-qa/ui/pnpm-lock.yaml
- examples/coagents-shared-state/ui/pnpm-lock.yaml
- examples/coagents-starter-crewai-flows/ui/pnpm-lock.yaml
- examples/coagents-starter/ui/pnpm-lock.yaml
- examples/copilot-anthropic-pinecone/pnpm-lock.yaml
- examples/copilot-form-filling/pnpm-lock.yaml
- examples/copilot-openaI-mongodb-atlas-vector-search/pnpm-lock.yaml
- examples/langgraph-tutorial-customer-support/ui/pnpm-lock.yaml
- examples/langgraph-tutorial-quickstart/ui/pnpm-lock.yaml
- examples/llamaindex/starter/ui/pnpm-lock.yaml
Dunno how this happened, but a bunch of pnpm lock files in the examples folders are out of sync, and it's blowing up deploys. 
NOW THEY CAN BE DEDESYNCED (I believe some people call that synced?)
> fix out of sync pnpm lockfiles

- docs/content/docs/adk/generative-ui/agentic.mdx
- docs/content/docs/adk/generative-ui/tool-based.mdx
- docs/content/docs/adk/quickstart.mdx
- docs/content/docs/adk/shared-state/in-app-agent-read.mdx
- docs/content/docs/adk/shared-state/in-app-agent-write.mdx
- docs/content/docs/pydantic-ai/generative-ui/tool-based.mdx
A lot of examples for the adk docs were not functioning or had formatting errors, this fixes most of them
> Fix all adk examples except hitl

- docs/content/docs/pydantic-ai/generative-ui/agentic.mdx
- docs/content/docs/pydantic-ai/generative-ui/tool-based.mdx
- docs/content/docs/pydantic-ai/shared-state/in-app-agent-read.mdx
- docs/content/docs/pydantic-ai/shared-state/in-app-agent-write.mdx
A few agents weren't aligned with the front end UI expectations so I updated them to match. 
Fixes both generative-ui pages and both shared-state pages.
> Fix pydantic-ai docs

- docs/content/docs/adk/generative-ui/agentic.mdx
- docs/content/docs/adk/human-in-the-loop/agent.mdx
- docs/content/docs/adk/shared-state/in-app-agent-read.mdx
- docs/content/docs/adk/shared-state/in-app-agent-write.mdx
- docs/content/docs/pydantic-ai/generative-ui/agentic.mdx
- Fixes a few miscellaneous typos
- Fixes the HITL demo for the ADK
- Updates pydantic-ai agentic chat demo to have better formatting
> Fix adk-hitl and a few typos
